// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vietgara/common/v1/bank_details.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BankDetails is a bank account that money is paid into. Shared by every
// record that carries one (suppliers today; the garage's legal profile and
// customers' tax profiles later).
type BankDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BankName      *string                `protobuf:"bytes,1,opt,name=bank_name,json=bankName,proto3,oneof" json:"bank_name,omitempty"`
	AccountNumber *string                `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3,oneof" json:"account_number,omitempty"`
	// Name the account is registered under.
	AccountHolder *string `protobuf:"bytes,3,opt,name=account_holder,json=accountHolder,proto3,oneof" json:"account_holder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankDetails) Reset() {
	*x = BankDetails{}
	mi := &file_vietgara_common_v1_bank_details_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankDetails) ProtoMessage() {}

func (x *BankDetails) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_common_v1_bank_details_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankDetails.ProtoReflect.Descriptor instead.
func (*BankDetails) Descriptor() ([]byte, []int) {
	return file_vietgara_common_v1_bank_details_proto_rawDescGZIP(), []int{0}
}

func (x *BankDetails) GetBankName() string {
	if x != nil && x.BankName != nil {
		return *x.BankName
	}
	return ""
}

func (x *BankDetails) GetAccountNumber() string {
	if x != nil && x.AccountNumber != nil {
		return *x.AccountNumber
	}
	return ""
}

func (x *BankDetails) GetAccountHolder() string {
	if x != nil && x.AccountHolder != nil {
		return *x.AccountHolder
	}
	return ""
}

var File_vietgara_common_v1_bank_details_proto protoreflect.FileDescriptor

const file_vietgara_common_v1_bank_details_proto_rawDesc = "" +
	"\n" +
	"%vietgara/common/v1/bank_details.proto\x12\x12vietgara.common.v1\"\xbb\x01\n" +
	"\vBankDetails\x12 \n" +
	"\tbank_name\x18\x01 \x01(\tH\x00R\bbankName\x88\x01\x01\x12*\n" +
	"\x0eaccount_number\x18\x02 \x01(\tH\x01R\raccountNumber\x88\x01\x01\x12*\n" +
	"\x0eaccount_holder\x18\x03 \x01(\tH\x02R\raccountHolder\x88\x01\x01B\f\n" +
	"\n" +
	"_bank_nameB\x11\n" +
	"\x0f_account_numberB\x11\n" +
	"\x0f_account_holderBJZHgithub.com/viettechno/vietgara-proto/apis-go/vietgara/common/v1;commonv1b\x06proto3"

var (
	file_vietgara_common_v1_bank_details_proto_rawDescOnce sync.Once
	file_vietgara_common_v1_bank_details_proto_rawDescData []byte
)

func file_vietgara_common_v1_bank_details_proto_rawDescGZIP() []byte {
	file_vietgara_common_v1_bank_details_proto_rawDescOnce.Do(func() {
		file_vietgara_common_v1_bank_details_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vietgara_common_v1_bank_details_proto_rawDesc), len(file_vietgara_common_v1_bank_details_proto_rawDesc)))
	})
	return file_vietgara_common_v1_bank_details_proto_rawDescData
}

var file_vietgara_common_v1_bank_details_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vietgara_common_v1_bank_details_proto_goTypes = []any{
	(*BankDetails)(nil), // 0: vietgara.common.v1.BankDetails
}
var file_vietgara_common_v1_bank_details_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vietgara_common_v1_bank_details_proto_init() }
func file_vietgara_common_v1_bank_details_proto_init() {
	if File_vietgara_common_v1_bank_details_proto != nil {
		return
	}
	file_vietgara_common_v1_bank_details_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vietgara_common_v1_bank_details_proto_rawDesc), len(file_vietgara_common_v1_bank_details_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vietgara_common_v1_bank_details_proto_goTypes,
		DependencyIndexes: file_vietgara_common_v1_bank_details_proto_depIdxs,
		MessageInfos:      file_vietgara_common_v1_bank_details_proto_msgTypes,
	}.Build()
	File_vietgara_common_v1_bank_details_proto = out.File
	file_vietgara_common_v1_bank_details_proto_goTypes = nil
	file_vietgara_common_v1_bank_details_proto_depIdxs = nil
}
