// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vietgara/common/v1/error.proto

package commonv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorResponse is the body of every non-2xx REST response:
// `{"error": {"code", "message", "details"}}`.
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_vietgara_common_v1_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_common_v1_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_common_v1_error_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Error describes why a request failed.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable, machine-readable code the client translates, e.g.
	// VALIDATION_ERROR, EMAIL_NOT_VERIFIED, OTP_EXPIRED, PLAN_LIMIT_REACHED.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// English, developer-facing description; clients show a localized text
	// for `code` instead.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Field-level problems for VALIDATION_ERROR.
	Details       []*ErrorDetail `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_vietgara_common_v1_error_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_common_v1_error_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_vietgara_common_v1_error_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() []*ErrorDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

// ErrorDetail is one invalid request field.
type ErrorDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON name of the field, e.g. "email" or "garage.name".
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Machine-readable problem: required, invalid, too_long, taken, ...
	Issue         string `protobuf:"bytes,2,opt,name=issue,proto3" json:"issue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_vietgara_common_v1_error_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_common_v1_error_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_vietgara_common_v1_error_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorDetail) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ErrorDetail) GetIssue() string {
	if x != nil {
		return x.Issue
	}
	return ""
}

var File_vietgara_common_v1_error_proto protoreflect.FileDescriptor

const file_vietgara_common_v1_error_proto_rawDesc = "" +
	"\n" +
	"\x1evietgara/common/v1/error.proto\x12\x12vietgara.common.v1\x1a.protoc-gen-openapiv2/options/annotations.proto\"@\n" +
	"\rErrorResponse\x12/\n" +
	"\x05error\x18\x01 \x01(\v2\x19.vietgara.common.v1.ErrorR\x05error\"p\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\adetails\x18\x03 \x03(\v2\x1f.vietgara.common.v1.ErrorDetailR\adetails\"9\n" +
	"\vErrorDetail\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x14\n" +
	"\x05issue\x18\x02 \x01(\tR\x05issueB\xb7\x03\x92A\xe9\x02\x12v\n" +
	"\fVietGara API\x12aPublic REST/JSON API of the VietGara platform (API Specification). Generated from vietgara-proto.2\x031.1*\x02\x01\x022\x10application/json:\x10application/jsonRZ\n" +
	"\adefault\x12O\n" +
	"&Error (API Specification Section 1.1).\x12%\n" +
	"#\x1a!.vietgara.common.v1.ErrorResponseZ]\n" +
	"[\n" +
	"\x06bearer\x12Q\b\x02\x12<Access token issued by the auth endpoints: `Bearer <token>`.\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00ZHgithub.com/viettechno/vietgara-proto/apis-go/vietgara/common/v1;commonv1b\x06proto3"

var (
	file_vietgara_common_v1_error_proto_rawDescOnce sync.Once
	file_vietgara_common_v1_error_proto_rawDescData []byte
)

func file_vietgara_common_v1_error_proto_rawDescGZIP() []byte {
	file_vietgara_common_v1_error_proto_rawDescOnce.Do(func() {
		file_vietgara_common_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vietgara_common_v1_error_proto_rawDesc), len(file_vietgara_common_v1_error_proto_rawDesc)))
	})
	return file_vietgara_common_v1_error_proto_rawDescData
}

var file_vietgara_common_v1_error_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vietgara_common_v1_error_proto_goTypes = []any{
	(*ErrorResponse)(nil), // 0: vietgara.common.v1.ErrorResponse
	(*Error)(nil),         // 1: vietgara.common.v1.Error
	(*ErrorDetail)(nil),   // 2: vietgara.common.v1.ErrorDetail
}
var file_vietgara_common_v1_error_proto_depIdxs = []int32{
	1, // 0: vietgara.common.v1.ErrorResponse.error:type_name -> vietgara.common.v1.Error
	2, // 1: vietgara.common.v1.Error.details:type_name -> vietgara.common.v1.ErrorDetail
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_vietgara_common_v1_error_proto_init() }
func file_vietgara_common_v1_error_proto_init() {
	if File_vietgara_common_v1_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vietgara_common_v1_error_proto_rawDesc), len(file_vietgara_common_v1_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vietgara_common_v1_error_proto_goTypes,
		DependencyIndexes: file_vietgara_common_v1_error_proto_depIdxs,
		MessageInfos:      file_vietgara_common_v1_error_proto_msgTypes,
	}.Build()
	File_vietgara_common_v1_error_proto = out.File
	file_vietgara_common_v1_error_proto_goTypes = nil
	file_vietgara_common_v1_error_proto_depIdxs = nil
}
