// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vietgara/tenant/v1/invitation.proto

package tenantv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvitationStatus int32

const (
	InvitationStatus_INVITATION_STATUS_UNSPECIFIED InvitationStatus = 0
	InvitationStatus_INVITATION_STATUS_PENDING     InvitationStatus = 1
	InvitationStatus_INVITATION_STATUS_ACCEPTED    InvitationStatus = 2
	InvitationStatus_INVITATION_STATUS_DECLINED    InvitationStatus = 3
	InvitationStatus_INVITATION_STATUS_REVOKED     InvitationStatus = 4
	InvitationStatus_INVITATION_STATUS_EXPIRED     InvitationStatus = 5
)

// Enum value maps for InvitationStatus.
var (
	InvitationStatus_name = map[int32]string{
		0: "INVITATION_STATUS_UNSPECIFIED",
		1: "INVITATION_STATUS_PENDING",
		2: "INVITATION_STATUS_ACCEPTED",
		3: "INVITATION_STATUS_DECLINED",
		4: "INVITATION_STATUS_REVOKED",
		5: "INVITATION_STATUS_EXPIRED",
	}
	InvitationStatus_value = map[string]int32{
		"INVITATION_STATUS_UNSPECIFIED": 0,
		"INVITATION_STATUS_PENDING":     1,
		"INVITATION_STATUS_ACCEPTED":    2,
		"INVITATION_STATUS_DECLINED":    3,
		"INVITATION_STATUS_REVOKED":     4,
		"INVITATION_STATUS_EXPIRED":     5,
	}
)

func (x InvitationStatus) Enum() *InvitationStatus {
	p := new(InvitationStatus)
	*p = x
	return p
}

func (x InvitationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvitationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_vietgara_tenant_v1_invitation_proto_enumTypes[0].Descriptor()
}

func (InvitationStatus) Type() protoreflect.EnumType {
	return &file_vietgara_tenant_v1_invitation_proto_enumTypes[0]
}

func (x InvitationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvitationStatus.Descriptor instead.
func (InvitationStatus) EnumDescriptor() ([]byte, []int) {
	return file_vietgara_tenant_v1_invitation_proto_rawDescGZIP(), []int{0}
}

// Invitation asks an existing user to join a garage (FR-TEN-04). It is
// e-mailed to the user and expires after 7 days.
type Invitation struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GarageId   string                 `protobuf:"bytes,2,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	GarageName string                 `protobuf:"bytes,3,opt,name=garage_name,json=garageName,proto3" json:"garage_name,omitempty"`
	UserId     string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FullName   string                 `protobuf:"bytes,5,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email      string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	// Staff groups the member joins on acceptance.
	GroupIds      []string               `protobuf:"bytes,7,rep,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"`
	Status        InvitationStatus       `protobuf:"varint,8,opt,name=status,proto3,enum=vietgara.tenant.v1.InvitationStatus" json:"status,omitempty"`
	InvitedByName string                 `protobuf:"bytes,9,opt,name=invited_by_name,json=invitedByName,proto3" json:"invited_by_name,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RespondedAt   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=responded_at,json=respondedAt,proto3" json:"responded_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invitation) Reset() {
	*x = Invitation{}
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invitation) ProtoMessage() {}

func (x *Invitation) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invitation.ProtoReflect.Descriptor instead.
func (*Invitation) Descriptor() ([]byte, []int) {
	return file_vietgara_tenant_v1_invitation_proto_rawDescGZIP(), []int{0}
}

func (x *Invitation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invitation) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *Invitation) GetGarageName() string {
	if x != nil {
		return x.GarageName
	}
	return ""
}

func (x *Invitation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Invitation) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Invitation) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Invitation) GetGroupIds() []string {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

func (x *Invitation) GetStatus() InvitationStatus {
	if x != nil {
		return x.Status
	}
	return InvitationStatus_INVITATION_STATUS_UNSPECIFIED
}

func (x *Invitation) GetInvitedByName() string {
	if x != nil {
		return x.InvitedByName
	}
	return ""
}

func (x *Invitation) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Invitation) GetRespondedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RespondedAt
	}
	return nil
}

func (x *Invitation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateInvitationRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	GarageId string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	// From LookupStaffCandidate.
	UserId        string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupIds      []string `protobuf:"bytes,3,rep,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvitationRequest) Reset() {
	*x = CreateInvitationRequest{}
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvitationRequest) ProtoMessage() {}

func (x *CreateInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvitationRequest.ProtoReflect.Descriptor instead.
func (*CreateInvitationRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_tenant_v1_invitation_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInvitationRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *CreateInvitationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateInvitationRequest) GetGroupIds() []string {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

type CreateInvitationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitation    *Invitation            `protobuf:"bytes,1,opt,name=invitation,proto3" json:"invitation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvitationResponse) Reset() {
	*x = CreateInvitationResponse{}
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvitationResponse) ProtoMessage() {}

func (x *CreateInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvitationResponse.ProtoReflect.Descriptor instead.
func (*CreateInvitationResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_tenant_v1_invitation_proto_rawDescGZIP(), []int{2}
}

func (x *CreateInvitationResponse) GetInvitation() *Invitation {
	if x != nil {
		return x.Invitation
	}
	return nil
}

type ListInvitationsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	GarageId string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	// Unspecified lists every status.
	Status        InvitationStatus `protobuf:"varint,2,opt,name=status,proto3,enum=vietgara.tenant.v1.InvitationStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvitationsRequest) Reset() {
	*x = ListInvitationsRequest{}
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitationsRequest) ProtoMessage() {}

func (x *ListInvitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvitationsRequest.ProtoReflect.Descriptor instead.
func (*ListInvitationsRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_tenant_v1_invitation_proto_rawDescGZIP(), []int{3}
}

func (x *ListInvitationsRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *ListInvitationsRequest) GetStatus() InvitationStatus {
	if x != nil {
		return x.Status
	}
	return InvitationStatus_INVITATION_STATUS_UNSPECIFIED
}

type ListInvitationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Invitation          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvitationsResponse) Reset() {
	*x = ListInvitationsResponse{}
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitationsResponse) ProtoMessage() {}

func (x *ListInvitationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvitationsResponse.ProtoReflect.Descriptor instead.
func (*ListInvitationsResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_tenant_v1_invitation_proto_rawDescGZIP(), []int{4}
}

func (x *ListInvitationsResponse) GetData() []*Invitation {
	if x != nil {
		return x.Data
	}
	return nil
}

type RevokeInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GarageId      string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	InvitationId  string                 `protobuf:"bytes,2,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeInvitationRequest) Reset() {
	*x = RevokeInvitationRequest{}
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeInvitationRequest) ProtoMessage() {}

func (x *RevokeInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeInvitationRequest.ProtoReflect.Descriptor instead.
func (*RevokeInvitationRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_tenant_v1_invitation_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeInvitationRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *RevokeInvitationRequest) GetInvitationId() string {
	if x != nil {
		return x.InvitationId
	}
	return ""
}

type RevokeInvitationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitation    *Invitation            `protobuf:"bytes,1,opt,name=invitation,proto3" json:"invitation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeInvitationResponse) Reset() {
	*x = RevokeInvitationResponse{}
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeInvitationResponse) ProtoMessage() {}

func (x *RevokeInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeInvitationResponse.ProtoReflect.Descriptor instead.
func (*RevokeInvitationResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_tenant_v1_invitation_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeInvitationResponse) GetInvitation() *Invitation {
	if x != nil {
		return x.Invitation
	}
	return nil
}

type ListMyInvitationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unspecified lists every status.
	Status        InvitationStatus `protobuf:"varint,1,opt,name=status,proto3,enum=vietgara.tenant.v1.InvitationStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyInvitationsRequest) Reset() {
	*x = ListMyInvitationsRequest{}
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyInvitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyInvitationsRequest) ProtoMessage() {}

func (x *ListMyInvitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyInvitationsRequest.ProtoReflect.Descriptor instead.
func (*ListMyInvitationsRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_tenant_v1_invitation_proto_rawDescGZIP(), []int{7}
}

func (x *ListMyInvitationsRequest) GetStatus() InvitationStatus {
	if x != nil {
		return x.Status
	}
	return InvitationStatus_INVITATION_STATUS_UNSPECIFIED
}

type ListMyInvitationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Invitation          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyInvitationsResponse) Reset() {
	*x = ListMyInvitationsResponse{}
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyInvitationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyInvitationsResponse) ProtoMessage() {}

func (x *ListMyInvitationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyInvitationsResponse.ProtoReflect.Descriptor instead.
func (*ListMyInvitationsResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_tenant_v1_invitation_proto_rawDescGZIP(), []int{8}
}

func (x *ListMyInvitationsResponse) GetData() []*Invitation {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetMyInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvitationId  string                 `protobuf:"bytes,1,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyInvitationRequest) Reset() {
	*x = GetMyInvitationRequest{}
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyInvitationRequest) ProtoMessage() {}

func (x *GetMyInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyInvitationRequest.ProtoReflect.Descriptor instead.
func (*GetMyInvitationRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_tenant_v1_invitation_proto_rawDescGZIP(), []int{9}
}

func (x *GetMyInvitationRequest) GetInvitationId() string {
	if x != nil {
		return x.InvitationId
	}
	return ""
}

type GetMyInvitationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitation    *Invitation            `protobuf:"bytes,1,opt,name=invitation,proto3" json:"invitation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyInvitationResponse) Reset() {
	*x = GetMyInvitationResponse{}
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyInvitationResponse) ProtoMessage() {}

func (x *GetMyInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyInvitationResponse.ProtoReflect.Descriptor instead.
func (*GetMyInvitationResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_tenant_v1_invitation_proto_rawDescGZIP(), []int{10}
}

func (x *GetMyInvitationResponse) GetInvitation() *Invitation {
	if x != nil {
		return x.Invitation
	}
	return nil
}

type AcceptInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvitationId  string                 `protobuf:"bytes,1,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInvitationRequest) Reset() {
	*x = AcceptInvitationRequest{}
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvitationRequest) ProtoMessage() {}

func (x *AcceptInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvitationRequest.ProtoReflect.Descriptor instead.
func (*AcceptInvitationRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_tenant_v1_invitation_proto_rawDescGZIP(), []int{11}
}

func (x *AcceptInvitationRequest) GetInvitationId() string {
	if x != nil {
		return x.InvitationId
	}
	return ""
}

type AcceptInvitationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitation    *Invitation            `protobuf:"bytes,1,opt,name=invitation,proto3" json:"invitation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInvitationResponse) Reset() {
	*x = AcceptInvitationResponse{}
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvitationResponse) ProtoMessage() {}

func (x *AcceptInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvitationResponse.ProtoReflect.Descriptor instead.
func (*AcceptInvitationResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_tenant_v1_invitation_proto_rawDescGZIP(), []int{12}
}

func (x *AcceptInvitationResponse) GetInvitation() *Invitation {
	if x != nil {
		return x.Invitation
	}
	return nil
}

type DeclineInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvitationId  string                 `protobuf:"bytes,1,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineInvitationRequest) Reset() {
	*x = DeclineInvitationRequest{}
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineInvitationRequest) ProtoMessage() {}

func (x *DeclineInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineInvitationRequest.ProtoReflect.Descriptor instead.
func (*DeclineInvitationRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_tenant_v1_invitation_proto_rawDescGZIP(), []int{13}
}

func (x *DeclineInvitationRequest) GetInvitationId() string {
	if x != nil {
		return x.InvitationId
	}
	return ""
}

type DeclineInvitationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitation    *Invitation            `protobuf:"bytes,1,opt,name=invitation,proto3" json:"invitation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineInvitationResponse) Reset() {
	*x = DeclineInvitationResponse{}
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineInvitationResponse) ProtoMessage() {}

func (x *DeclineInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_tenant_v1_invitation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineInvitationResponse.ProtoReflect.Descriptor instead.
func (*DeclineInvitationResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_tenant_v1_invitation_proto_rawDescGZIP(), []int{14}
}

func (x *DeclineInvitationResponse) GetInvitation() *Invitation {
	if x != nil {
		return x.Invitation
	}
	return nil
}

var File_vietgara_tenant_v1_invitation_proto protoreflect.FileDescriptor

const file_vietgara_tenant_v1_invitation_proto_rawDesc = "" +
	"\n" +
	"#vietgara/tenant/v1/invitation.proto\x12\x12vietgara.tenant.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x04\n" +
	"\n" +
	"Invitation\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x03R\x02id\x12 \n" +
	"\tgarage_id\x18\x02 \x01(\tB\x03\xe0A\x03R\bgarageId\x12$\n" +
	"\vgarage_name\x18\x03 \x01(\tB\x03\xe0A\x03R\n" +
	"garageName\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12 \n" +
	"\tfull_name\x18\x05 \x01(\tB\x03\xe0A\x03R\bfullName\x12\x19\n" +
	"\x05email\x18\x06 \x01(\tB\x03\xe0A\x03R\x05email\x12\x1b\n" +
	"\tgroup_ids\x18\a \x03(\tR\bgroupIds\x12A\n" +
	"\x06status\x18\b \x01(\x0e2$.vietgara.tenant.v1.InvitationStatusB\x03\xe0A\x03R\x06status\x12+\n" +
	"\x0finvited_by_name\x18\t \x01(\tB\x03\xe0A\x03R\rinvitedByName\x12>\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\texpiresAt\x12B\n" +
	"\fresponded_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\vrespondedAt\x12>\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tcreatedAt\"v\n" +
	"\x17CreateInvitationRequest\x12 \n" +
	"\tgarage_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bgarageId\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\tB\x03\xe0A\x02R\x06userId\x12\x1b\n" +
	"\tgroup_ids\x18\x03 \x03(\tR\bgroupIds\"Z\n" +
	"\x18CreateInvitationResponse\x12>\n" +
	"\n" +
	"invitation\x18\x01 \x01(\v2\x1e.vietgara.tenant.v1.InvitationR\n" +
	"invitation\"x\n" +
	"\x16ListInvitationsRequest\x12 \n" +
	"\tgarage_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bgarageId\x12<\n" +
	"\x06status\x18\x02 \x01(\x0e2$.vietgara.tenant.v1.InvitationStatusR\x06status\"M\n" +
	"\x17ListInvitationsResponse\x122\n" +
	"\x04data\x18\x01 \x03(\v2\x1e.vietgara.tenant.v1.InvitationR\x04data\"e\n" +
	"\x17RevokeInvitationRequest\x12 \n" +
	"\tgarage_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bgarageId\x12(\n" +
	"\rinvitation_id\x18\x02 \x01(\tB\x03\xe0A\x02R\finvitationId\"Z\n" +
	"\x18RevokeInvitationResponse\x12>\n" +
	"\n" +
	"invitation\x18\x01 \x01(\v2\x1e.vietgara.tenant.v1.InvitationR\n" +
	"invitation\"X\n" +
	"\x18ListMyInvitationsRequest\x12<\n" +
	"\x06status\x18\x01 \x01(\x0e2$.vietgara.tenant.v1.InvitationStatusR\x06status\"O\n" +
	"\x19ListMyInvitationsResponse\x122\n" +
	"\x04data\x18\x01 \x03(\v2\x1e.vietgara.tenant.v1.InvitationR\x04data\"B\n" +
	"\x16GetMyInvitationRequest\x12(\n" +
	"\rinvitation_id\x18\x01 \x01(\tB\x03\xe0A\x02R\finvitationId\"Y\n" +
	"\x17GetMyInvitationResponse\x12>\n" +
	"\n" +
	"invitation\x18\x01 \x01(\v2\x1e.vietgara.tenant.v1.InvitationR\n" +
	"invitation\"C\n" +
	"\x17AcceptInvitationRequest\x12(\n" +
	"\rinvitation_id\x18\x01 \x01(\tB\x03\xe0A\x02R\finvitationId\"Z\n" +
	"\x18AcceptInvitationResponse\x12>\n" +
	"\n" +
	"invitation\x18\x01 \x01(\v2\x1e.vietgara.tenant.v1.InvitationR\n" +
	"invitation\"D\n" +
	"\x18DeclineInvitationRequest\x12(\n" +
	"\rinvitation_id\x18\x01 \x01(\tB\x03\xe0A\x02R\finvitationId\"[\n" +
	"\x19DeclineInvitationResponse\x12>\n" +
	"\n" +
	"invitation\x18\x01 \x01(\v2\x1e.vietgara.tenant.v1.InvitationR\n" +
	"invitation*\xd2\x01\n" +
	"\x10InvitationStatus\x12!\n" +
	"\x1dINVITATION_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19INVITATION_STATUS_PENDING\x10\x01\x12\x1e\n" +
	"\x1aINVITATION_STATUS_ACCEPTED\x10\x02\x12\x1e\n" +
	"\x1aINVITATION_STATUS_DECLINED\x10\x03\x12\x1d\n" +
	"\x19INVITATION_STATUS_REVOKED\x10\x04\x12\x1d\n" +
	"\x19INVITATION_STATUS_EXPIRED\x10\x052\xd4\t\n" +
	"\x11InvitationService\x12\xad\x01\n" +
	"\x10CreateInvitation\x12+.vietgara.tenant.v1.CreateInvitationRequest\x1a,.vietgara.tenant.v1.CreateInvitationResponse\">\x82\xd3\xe4\x93\x028:\x01*b\n" +
	"invitation\"'/api/v1/garages/{garage_id}/invitations\x12\x9b\x01\n" +
	"\x0fListInvitations\x12*.vietgara.tenant.v1.ListInvitationsRequest\x1a+.vietgara.tenant.v1.ListInvitationsResponse\"/\x82\xd3\xe4\x93\x02)\x12'/api/v1/garages/{garage_id}/invitations\x12\xc4\x01\n" +
	"\x10RevokeInvitation\x12+.vietgara.tenant.v1.RevokeInvitationRequest\x1a,.vietgara.tenant.v1.RevokeInvitationResponse\"U\x82\xd3\xe4\x93\x02O:\x01*b\n" +
	"invitation\">/api/v1/garages/{garage_id}/invitations/{invitation_id}/revoke\x12\x90\x01\n" +
	"\x11ListMyInvitations\x12,.vietgara.tenant.v1.ListMyInvitationsRequest\x1a-.vietgara.tenant.v1.ListMyInvitationsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/me/invitations\x12\xa6\x01\n" +
	"\x0fGetMyInvitation\x12*.vietgara.tenant.v1.GetMyInvitationRequest\x1a+.vietgara.tenant.v1.GetMyInvitationResponse\":\x82\xd3\xe4\x93\x024b\n" +
	"invitation\x12&/api/v1/me/invitations/{invitation_id}\x12\xb3\x01\n" +
	"\x10AcceptInvitation\x12+.vietgara.tenant.v1.AcceptInvitationRequest\x1a,.vietgara.tenant.v1.AcceptInvitationResponse\"D\x82\xd3\xe4\x93\x02>:\x01*b\n" +
	"invitation\"-/api/v1/me/invitations/{invitation_id}/accept\x12\xb7\x01\n" +
	"\x11DeclineInvitation\x12,.vietgara.tenant.v1.DeclineInvitationRequest\x1a-.vietgara.tenant.v1.DeclineInvitationResponse\"E\x82\xd3\xe4\x93\x02?:\x01*b\n" +
	"invitation\"./api/v1/me/invitations/{invitation_id}/declineBJZHgithub.com/viettechno/vietgara-proto/apis-go/vietgara/tenant/v1;tenantv1b\x06proto3"

var (
	file_vietgara_tenant_v1_invitation_proto_rawDescOnce sync.Once
	file_vietgara_tenant_v1_invitation_proto_rawDescData []byte
)

func file_vietgara_tenant_v1_invitation_proto_rawDescGZIP() []byte {
	file_vietgara_tenant_v1_invitation_proto_rawDescOnce.Do(func() {
		file_vietgara_tenant_v1_invitation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vietgara_tenant_v1_invitation_proto_rawDesc), len(file_vietgara_tenant_v1_invitation_proto_rawDesc)))
	})
	return file_vietgara_tenant_v1_invitation_proto_rawDescData
}

var file_vietgara_tenant_v1_invitation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vietgara_tenant_v1_invitation_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_vietgara_tenant_v1_invitation_proto_goTypes = []any{
	(InvitationStatus)(0),             // 0: vietgara.tenant.v1.InvitationStatus
	(*Invitation)(nil),                // 1: vietgara.tenant.v1.Invitation
	(*CreateInvitationRequest)(nil),   // 2: vietgara.tenant.v1.CreateInvitationRequest
	(*CreateInvitationResponse)(nil),  // 3: vietgara.tenant.v1.CreateInvitationResponse
	(*ListInvitationsRequest)(nil),    // 4: vietgara.tenant.v1.ListInvitationsRequest
	(*ListInvitationsResponse)(nil),   // 5: vietgara.tenant.v1.ListInvitationsResponse
	(*RevokeInvitationRequest)(nil),   // 6: vietgara.tenant.v1.RevokeInvitationRequest
	(*RevokeInvitationResponse)(nil),  // 7: vietgara.tenant.v1.RevokeInvitationResponse
	(*ListMyInvitationsRequest)(nil),  // 8: vietgara.tenant.v1.ListMyInvitationsRequest
	(*ListMyInvitationsResponse)(nil), // 9: vietgara.tenant.v1.ListMyInvitationsResponse
	(*GetMyInvitationRequest)(nil),    // 10: vietgara.tenant.v1.GetMyInvitationRequest
	(*GetMyInvitationResponse)(nil),   // 11: vietgara.tenant.v1.GetMyInvitationResponse
	(*AcceptInvitationRequest)(nil),   // 12: vietgara.tenant.v1.AcceptInvitationRequest
	(*AcceptInvitationResponse)(nil),  // 13: vietgara.tenant.v1.AcceptInvitationResponse
	(*DeclineInvitationRequest)(nil),  // 14: vietgara.tenant.v1.DeclineInvitationRequest
	(*DeclineInvitationResponse)(nil), // 15: vietgara.tenant.v1.DeclineInvitationResponse
	(*timestamppb.Timestamp)(nil),     // 16: google.protobuf.Timestamp
}
var file_vietgara_tenant_v1_invitation_proto_depIdxs = []int32{
	0,  // 0: vietgara.tenant.v1.Invitation.status:type_name -> vietgara.tenant.v1.InvitationStatus
	16, // 1: vietgara.tenant.v1.Invitation.expires_at:type_name -> google.protobuf.Timestamp
	16, // 2: vietgara.tenant.v1.Invitation.responded_at:type_name -> google.protobuf.Timestamp
	16, // 3: vietgara.tenant.v1.Invitation.created_at:type_name -> google.protobuf.Timestamp
	1,  // 4: vietgara.tenant.v1.CreateInvitationResponse.invitation:type_name -> vietgara.tenant.v1.Invitation
	0,  // 5: vietgara.tenant.v1.ListInvitationsRequest.status:type_name -> vietgara.tenant.v1.InvitationStatus
	1,  // 6: vietgara.tenant.v1.ListInvitationsResponse.data:type_name -> vietgara.tenant.v1.Invitation
	1,  // 7: vietgara.tenant.v1.RevokeInvitationResponse.invitation:type_name -> vietgara.tenant.v1.Invitation
	0,  // 8: vietgara.tenant.v1.ListMyInvitationsRequest.status:type_name -> vietgara.tenant.v1.InvitationStatus
	1,  // 9: vietgara.tenant.v1.ListMyInvitationsResponse.data:type_name -> vietgara.tenant.v1.Invitation
	1,  // 10: vietgara.tenant.v1.GetMyInvitationResponse.invitation:type_name -> vietgara.tenant.v1.Invitation
	1,  // 11: vietgara.tenant.v1.AcceptInvitationResponse.invitation:type_name -> vietgara.tenant.v1.Invitation
	1,  // 12: vietgara.tenant.v1.DeclineInvitationResponse.invitation:type_name -> vietgara.tenant.v1.Invitation
	2,  // 13: vietgara.tenant.v1.InvitationService.CreateInvitation:input_type -> vietgara.tenant.v1.CreateInvitationRequest
	4,  // 14: vietgara.tenant.v1.InvitationService.ListInvitations:input_type -> vietgara.tenant.v1.ListInvitationsRequest
	6,  // 15: vietgara.tenant.v1.InvitationService.RevokeInvitation:input_type -> vietgara.tenant.v1.RevokeInvitationRequest
	8,  // 16: vietgara.tenant.v1.InvitationService.ListMyInvitations:input_type -> vietgara.tenant.v1.ListMyInvitationsRequest
	10, // 17: vietgara.tenant.v1.InvitationService.GetMyInvitation:input_type -> vietgara.tenant.v1.GetMyInvitationRequest
	12, // 18: vietgara.tenant.v1.InvitationService.AcceptInvitation:input_type -> vietgara.tenant.v1.AcceptInvitationRequest
	14, // 19: vietgara.tenant.v1.InvitationService.DeclineInvitation:input_type -> vietgara.tenant.v1.DeclineInvitationRequest
	3,  // 20: vietgara.tenant.v1.InvitationService.CreateInvitation:output_type -> vietgara.tenant.v1.CreateInvitationResponse
	5,  // 21: vietgara.tenant.v1.InvitationService.ListInvitations:output_type -> vietgara.tenant.v1.ListInvitationsResponse
	7,  // 22: vietgara.tenant.v1.InvitationService.RevokeInvitation:output_type -> vietgara.tenant.v1.RevokeInvitationResponse
	9,  // 23: vietgara.tenant.v1.InvitationService.ListMyInvitations:output_type -> vietgara.tenant.v1.ListMyInvitationsResponse
	11, // 24: vietgara.tenant.v1.InvitationService.GetMyInvitation:output_type -> vietgara.tenant.v1.GetMyInvitationResponse
	13, // 25: vietgara.tenant.v1.InvitationService.AcceptInvitation:output_type -> vietgara.tenant.v1.AcceptInvitationResponse
	15, // 26: vietgara.tenant.v1.InvitationService.DeclineInvitation:output_type -> vietgara.tenant.v1.DeclineInvitationResponse
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_vietgara_tenant_v1_invitation_proto_init() }
func file_vietgara_tenant_v1_invitation_proto_init() {
	if File_vietgara_tenant_v1_invitation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vietgara_tenant_v1_invitation_proto_rawDesc), len(file_vietgara_tenant_v1_invitation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vietgara_tenant_v1_invitation_proto_goTypes,
		DependencyIndexes: file_vietgara_tenant_v1_invitation_proto_depIdxs,
		EnumInfos:         file_vietgara_tenant_v1_invitation_proto_enumTypes,
		MessageInfos:      file_vietgara_tenant_v1_invitation_proto_msgTypes,
	}.Build()
	File_vietgara_tenant_v1_invitation_proto = out.File
	file_vietgara_tenant_v1_invitation_proto_goTypes = nil
	file_vietgara_tenant_v1_invitation_proto_depIdxs = nil
}
