// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: vietgara/document/v1/document.proto

package documentv1

import (
	context "context"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentService_ExportQuotePdf_FullMethodName             = "/vietgara.document.v1.DocumentService/ExportQuotePdf"
	DocumentService_ExportRepairOrderPdf_FullMethodName       = "/vietgara.document.v1.DocumentService/ExportRepairOrderPdf"
	DocumentService_ExportSettlementReceiptPdf_FullMethodName = "/vietgara.document.v1.DocumentService/ExportSettlementReceiptPdf"
	DocumentService_ExportStockMovementsExcel_FullMethodName  = "/vietgara.document.v1.DocumentService/ExportStockMovementsExcel"
)

// DocumentServiceClient is the client API for DocumentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DocumentService renders PDFs and Excel reports on request (FRD 3.13).
// No templates are stored -- FR-DOC-03 (letting a garage customize the
// logo and layout) is Phase 4 -- every document is generated fresh from
// the owning module's own data, read through a narrow interface the same
// way every other cross-module read works (HLD Section 2: a module never
// queries another module's tables directly). Each RPC needs the same
// permission as the data it renders (quote.read, billing.read,
// inventory.read), not a permission of its own.
type DocumentServiceClient interface {
	// FR-DOC-01: the quote as a PDF, using the garage's standard layout.
	ExportQuotePdf(ctx context.Context, in *ExportQuotePdfRequest, opts ...grpc.CallOption) (*httpbody.HttpBody, error)
	// FR-DOC-01: the repair order as a PDF, using the garage's standard
	// layout.
	ExportRepairOrderPdf(ctx context.Context, in *ExportRepairOrderPdfRequest, opts ...grpc.CallOption) (*httpbody.HttpBody, error)
	// FR-DOC-01: the settlement as a receipt PDF.
	ExportSettlementReceiptPdf(ctx context.Context, in *ExportSettlementReceiptPdfRequest, opts ...grpc.CallOption) (*httpbody.HttpBody, error)
	// FR-DOC-02: the stock in/out/on-hand movement report (FR-INV-05) as an
	// Excel workbook; same filter as the JSON report
	// (InventoryService.ListStockTransactions).
	ExportStockMovementsExcel(ctx context.Context, in *ExportStockMovementsExcelRequest, opts ...grpc.CallOption) (*httpbody.HttpBody, error)
}

type documentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentServiceClient(cc grpc.ClientConnInterface) DocumentServiceClient {
	return &documentServiceClient{cc}
}

func (c *documentServiceClient) ExportQuotePdf(ctx context.Context, in *ExportQuotePdfRequest, opts ...grpc.CallOption) (*httpbody.HttpBody, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(httpbody.HttpBody)
	err := c.cc.Invoke(ctx, DocumentService_ExportQuotePdf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) ExportRepairOrderPdf(ctx context.Context, in *ExportRepairOrderPdfRequest, opts ...grpc.CallOption) (*httpbody.HttpBody, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(httpbody.HttpBody)
	err := c.cc.Invoke(ctx, DocumentService_ExportRepairOrderPdf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) ExportSettlementReceiptPdf(ctx context.Context, in *ExportSettlementReceiptPdfRequest, opts ...grpc.CallOption) (*httpbody.HttpBody, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(httpbody.HttpBody)
	err := c.cc.Invoke(ctx, DocumentService_ExportSettlementReceiptPdf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) ExportStockMovementsExcel(ctx context.Context, in *ExportStockMovementsExcelRequest, opts ...grpc.CallOption) (*httpbody.HttpBody, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(httpbody.HttpBody)
	err := c.cc.Invoke(ctx, DocumentService_ExportStockMovementsExcel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentServiceServer is the server API for DocumentService service.
// All implementations must embed UnimplementedDocumentServiceServer
// for forward compatibility.
//
// DocumentService renders PDFs and Excel reports on request (FRD 3.13).
// No templates are stored -- FR-DOC-03 (letting a garage customize the
// logo and layout) is Phase 4 -- every document is generated fresh from
// the owning module's own data, read through a narrow interface the same
// way every other cross-module read works (HLD Section 2: a module never
// queries another module's tables directly). Each RPC needs the same
// permission as the data it renders (quote.read, billing.read,
// inventory.read), not a permission of its own.
type DocumentServiceServer interface {
	// FR-DOC-01: the quote as a PDF, using the garage's standard layout.
	ExportQuotePdf(context.Context, *ExportQuotePdfRequest) (*httpbody.HttpBody, error)
	// FR-DOC-01: the repair order as a PDF, using the garage's standard
	// layout.
	ExportRepairOrderPdf(context.Context, *ExportRepairOrderPdfRequest) (*httpbody.HttpBody, error)
	// FR-DOC-01: the settlement as a receipt PDF.
	ExportSettlementReceiptPdf(context.Context, *ExportSettlementReceiptPdfRequest) (*httpbody.HttpBody, error)
	// FR-DOC-02: the stock in/out/on-hand movement report (FR-INV-05) as an
	// Excel workbook; same filter as the JSON report
	// (InventoryService.ListStockTransactions).
	ExportStockMovementsExcel(context.Context, *ExportStockMovementsExcelRequest) (*httpbody.HttpBody, error)
	mustEmbedUnimplementedDocumentServiceServer()
}

// UnimplementedDocumentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentServiceServer struct{}

func (UnimplementedDocumentServiceServer) ExportQuotePdf(context.Context, *ExportQuotePdfRequest) (*httpbody.HttpBody, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportQuotePdf not implemented")
}
func (UnimplementedDocumentServiceServer) ExportRepairOrderPdf(context.Context, *ExportRepairOrderPdfRequest) (*httpbody.HttpBody, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportRepairOrderPdf not implemented")
}
func (UnimplementedDocumentServiceServer) ExportSettlementReceiptPdf(context.Context, *ExportSettlementReceiptPdfRequest) (*httpbody.HttpBody, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportSettlementReceiptPdf not implemented")
}
func (UnimplementedDocumentServiceServer) ExportStockMovementsExcel(context.Context, *ExportStockMovementsExcelRequest) (*httpbody.HttpBody, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportStockMovementsExcel not implemented")
}
func (UnimplementedDocumentServiceServer) mustEmbedUnimplementedDocumentServiceServer() {}
func (UnimplementedDocumentServiceServer) testEmbeddedByValue()                         {}

// UnsafeDocumentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentServiceServer will
// result in compilation errors.
type UnsafeDocumentServiceServer interface {
	mustEmbedUnimplementedDocumentServiceServer()
}

func RegisterDocumentServiceServer(s grpc.ServiceRegistrar, srv DocumentServiceServer) {
	// If the following call panics, it indicates UnimplementedDocumentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentService_ServiceDesc, srv)
}

func _DocumentService_ExportQuotePdf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportQuotePdfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).ExportQuotePdf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_ExportQuotePdf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).ExportQuotePdf(ctx, req.(*ExportQuotePdfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_ExportRepairOrderPdf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportRepairOrderPdfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).ExportRepairOrderPdf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_ExportRepairOrderPdf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).ExportRepairOrderPdf(ctx, req.(*ExportRepairOrderPdfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_ExportSettlementReceiptPdf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportSettlementReceiptPdfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).ExportSettlementReceiptPdf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_ExportSettlementReceiptPdf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).ExportSettlementReceiptPdf(ctx, req.(*ExportSettlementReceiptPdfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_ExportStockMovementsExcel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportStockMovementsExcelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).ExportStockMovementsExcel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_ExportStockMovementsExcel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).ExportStockMovementsExcel(ctx, req.(*ExportStockMovementsExcelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentService_ServiceDesc is the grpc.ServiceDesc for DocumentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vietgara.document.v1.DocumentService",
	HandlerType: (*DocumentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExportQuotePdf",
			Handler:    _DocumentService_ExportQuotePdf_Handler,
		},
		{
			MethodName: "ExportRepairOrderPdf",
			Handler:    _DocumentService_ExportRepairOrderPdf_Handler,
		},
		{
			MethodName: "ExportSettlementReceiptPdf",
			Handler:    _DocumentService_ExportSettlementReceiptPdf_Handler,
		},
		{
			MethodName: "ExportStockMovementsExcel",
			Handler:    _DocumentService_ExportStockMovementsExcel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vietgara/document/v1/document.proto",
}
