// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: vietgara/customerportal/v1/customer_portal.proto

/*
Package customerportalv1 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package customerportalv1

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var (
	_ codes.Code
	_ io.Reader
	_ status.Status
	_ = errors.New
	_ = runtime.String
	_ = utilities.NewDoubleArray
	_ = metadata.Join
)

func request_CustomerPortalService_ListMyVehicles_0(ctx context.Context, marshaler runtime.Marshaler, client CustomerPortalServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq ListMyVehiclesRequest
		metadata runtime.ServerMetadata
	)
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	msg, err := client.ListMyVehicles(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_CustomerPortalService_ListMyVehicles_0(ctx context.Context, marshaler runtime.Marshaler, server CustomerPortalServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq ListMyVehiclesRequest
		metadata runtime.ServerMetadata
	)
	msg, err := server.ListMyVehicles(ctx, &protoReq)
	return msg, metadata, err
}

func request_CustomerPortalService_GetMyVehicleHistory_0(ctx context.Context, marshaler runtime.Marshaler, client CustomerPortalServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetMyVehicleHistoryRequest
		metadata runtime.ServerMetadata
		err      error
	)
	val, ok := pathParams["garage_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "garage_id")
	}
	protoReq.GarageId, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "garage_id", err)
	}
	val, ok = pathParams["vehicle_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "vehicle_id")
	}
	protoReq.VehicleId, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "vehicle_id", err)
	}
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	msg, err := client.GetMyVehicleHistory(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_CustomerPortalService_GetMyVehicleHistory_0(ctx context.Context, marshaler runtime.Marshaler, server CustomerPortalServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq GetMyVehicleHistoryRequest
		metadata runtime.ServerMetadata
		err      error
	)
	val, ok := pathParams["garage_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "garage_id")
	}
	protoReq.GarageId, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "garage_id", err)
	}
	val, ok = pathParams["vehicle_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "vehicle_id")
	}
	protoReq.VehicleId, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "vehicle_id", err)
	}
	msg, err := server.GetMyVehicleHistory(ctx, &protoReq)
	return msg, metadata, err
}

// RegisterCustomerPortalServiceHandlerServer registers the http handlers for service CustomerPortalService to "mux".
// UnaryRPC     :call CustomerPortalServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterCustomerPortalServiceHandlerFromEndpoint instead.
// GRPC interceptors will not work for this type of registration. To use interceptors, you must use the "runtime.WithMiddlewares" option in the "runtime.NewServeMux" call.
func RegisterCustomerPortalServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server CustomerPortalServiceServer) error {
	mux.Handle(http.MethodGet, pattern_CustomerPortalService_ListMyVehicles_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/vietgara.customerportal.v1.CustomerPortalService/ListMyVehicles", runtime.WithHTTPPathPattern("/api/v1/customer/vehicles"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_CustomerPortalService_ListMyVehicles_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_CustomerPortalService_ListMyVehicles_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_CustomerPortalService_GetMyVehicleHistory_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/vietgara.customerportal.v1.CustomerPortalService/GetMyVehicleHistory", runtime.WithHTTPPathPattern("/api/v1/customer/garages/{garage_id}/vehicles/{vehicle_id}/history"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_CustomerPortalService_GetMyVehicleHistory_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_CustomerPortalService_GetMyVehicleHistory_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})

	return nil
}

// RegisterCustomerPortalServiceHandlerFromEndpoint is same as RegisterCustomerPortalServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterCustomerPortalServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.NewClient(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()
	return RegisterCustomerPortalServiceHandler(ctx, mux, conn)
}

// RegisterCustomerPortalServiceHandler registers the http handlers for service CustomerPortalService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterCustomerPortalServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterCustomerPortalServiceHandlerClient(ctx, mux, NewCustomerPortalServiceClient(conn))
}

// RegisterCustomerPortalServiceHandlerClient registers the http handlers for service CustomerPortalService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "CustomerPortalServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "CustomerPortalServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "CustomerPortalServiceClient" to call the correct interceptors. This client ignores the HTTP middlewares.
func RegisterCustomerPortalServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client CustomerPortalServiceClient) error {
	mux.Handle(http.MethodGet, pattern_CustomerPortalService_ListMyVehicles_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/vietgara.customerportal.v1.CustomerPortalService/ListMyVehicles", runtime.WithHTTPPathPattern("/api/v1/customer/vehicles"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_CustomerPortalService_ListMyVehicles_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_CustomerPortalService_ListMyVehicles_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_CustomerPortalService_GetMyVehicleHistory_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/vietgara.customerportal.v1.CustomerPortalService/GetMyVehicleHistory", runtime.WithHTTPPathPattern("/api/v1/customer/garages/{garage_id}/vehicles/{vehicle_id}/history"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_CustomerPortalService_GetMyVehicleHistory_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_CustomerPortalService_GetMyVehicleHistory_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	return nil
}

var (
	pattern_CustomerPortalService_ListMyVehicles_0      = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3}, []string{"api", "v1", "customer", "vehicles"}, ""))
	pattern_CustomerPortalService_GetMyVehicleHistory_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 1, 0, 4, 1, 5, 4, 2, 5, 1, 0, 4, 1, 5, 6, 2, 7}, []string{"api", "v1", "customer", "garages", "garage_id", "vehicles", "vehicle_id", "history"}, ""))
)

var (
	forward_CustomerPortalService_ListMyVehicles_0      = runtime.ForwardResponseMessage
	forward_CustomerPortalService_GetMyVehicleHistory_0 = runtime.ForwardResponseMessage
)
