// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: vietgara/customerportal/v1/customer_portal.proto

package customerportalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CustomerPortalService_ListMyVehicles_FullMethodName      = "/vietgara.customerportal.v1.CustomerPortalService/ListMyVehicles"
	CustomerPortalService_ListMyGarageLinks_FullMethodName   = "/vietgara.customerportal.v1.CustomerPortalService/ListMyGarageLinks"
	CustomerPortalService_AcceptGarageLink_FullMethodName    = "/vietgara.customerportal.v1.CustomerPortalService/AcceptGarageLink"
	CustomerPortalService_DeclineGarageLink_FullMethodName   = "/vietgara.customerportal.v1.CustomerPortalService/DeclineGarageLink"
	CustomerPortalService_UnlinkGarageLink_FullMethodName    = "/vietgara.customerportal.v1.CustomerPortalService/UnlinkGarageLink"
	CustomerPortalService_GetMyVehicleHistory_FullMethodName = "/vietgara.customerportal.v1.CustomerPortalService/GetMyVehicleHistory"
)

// CustomerPortalServiceClient is the client API for CustomerPortalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CustomerPortalService is the Customer BFF (Release 2.4, HLD Section 6).
// The caller is a VietGara user -- in Release 2.4 created by Google
// sign-in (FR-CAPP-01) -- matched to garages' customer records by its
// verified e-mail. It never reads garage data beyond those records, their
// vehicles and the vehicles' history.
type CustomerPortalServiceClient interface {
	// The signed-in person's vehicles, grouped by garage (FR-CAPP-02).
	ListMyVehicles(ctx context.Context, in *ListMyVehiclesRequest, opts ...grpc.CallOption) (*ListMyVehiclesResponse, error)
	// FR-CAPP-05: link requests from garages and the garages already linked.
	ListMyGarageLinks(ctx context.Context, in *ListMyGarageLinksRequest, opts ...grpc.CallOption) (*ListMyGarageLinksResponse, error)
	// Accepts a garage's request to link the user with its customer profile.
	AcceptGarageLink(ctx context.Context, in *AcceptGarageLinkRequest, opts ...grpc.CallOption) (*AcceptGarageLinkResponse, error)
	DeclineGarageLink(ctx context.Context, in *DeclineGarageLinkRequest, opts ...grpc.CallOption) (*DeclineGarageLinkResponse, error)
	// Ends a link from the user's side.
	UnlinkGarageLink(ctx context.Context, in *UnlinkGarageLinkRequest, opts ...grpc.CallOption) (*UnlinkGarageLinkResponse, error)
	// One of the person's vehicles' repair history (FR-CAPP-02, FR-CUS-03);
	// NOT_FOUND unless the vehicle belongs to their customer record there.
	GetMyVehicleHistory(ctx context.Context, in *GetMyVehicleHistoryRequest, opts ...grpc.CallOption) (*GetMyVehicleHistoryResponse, error)
}

type customerPortalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomerPortalServiceClient(cc grpc.ClientConnInterface) CustomerPortalServiceClient {
	return &customerPortalServiceClient{cc}
}

func (c *customerPortalServiceClient) ListMyVehicles(ctx context.Context, in *ListMyVehiclesRequest, opts ...grpc.CallOption) (*ListMyVehiclesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyVehiclesResponse)
	err := c.cc.Invoke(ctx, CustomerPortalService_ListMyVehicles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerPortalServiceClient) ListMyGarageLinks(ctx context.Context, in *ListMyGarageLinksRequest, opts ...grpc.CallOption) (*ListMyGarageLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyGarageLinksResponse)
	err := c.cc.Invoke(ctx, CustomerPortalService_ListMyGarageLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerPortalServiceClient) AcceptGarageLink(ctx context.Context, in *AcceptGarageLinkRequest, opts ...grpc.CallOption) (*AcceptGarageLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptGarageLinkResponse)
	err := c.cc.Invoke(ctx, CustomerPortalService_AcceptGarageLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerPortalServiceClient) DeclineGarageLink(ctx context.Context, in *DeclineGarageLinkRequest, opts ...grpc.CallOption) (*DeclineGarageLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeclineGarageLinkResponse)
	err := c.cc.Invoke(ctx, CustomerPortalService_DeclineGarageLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerPortalServiceClient) UnlinkGarageLink(ctx context.Context, in *UnlinkGarageLinkRequest, opts ...grpc.CallOption) (*UnlinkGarageLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlinkGarageLinkResponse)
	err := c.cc.Invoke(ctx, CustomerPortalService_UnlinkGarageLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerPortalServiceClient) GetMyVehicleHistory(ctx context.Context, in *GetMyVehicleHistoryRequest, opts ...grpc.CallOption) (*GetMyVehicleHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyVehicleHistoryResponse)
	err := c.cc.Invoke(ctx, CustomerPortalService_GetMyVehicleHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerPortalServiceServer is the server API for CustomerPortalService service.
// All implementations must embed UnimplementedCustomerPortalServiceServer
// for forward compatibility.
//
// CustomerPortalService is the Customer BFF (Release 2.4, HLD Section 6).
// The caller is a VietGara user -- in Release 2.4 created by Google
// sign-in (FR-CAPP-01) -- matched to garages' customer records by its
// verified e-mail. It never reads garage data beyond those records, their
// vehicles and the vehicles' history.
type CustomerPortalServiceServer interface {
	// The signed-in person's vehicles, grouped by garage (FR-CAPP-02).
	ListMyVehicles(context.Context, *ListMyVehiclesRequest) (*ListMyVehiclesResponse, error)
	// FR-CAPP-05: link requests from garages and the garages already linked.
	ListMyGarageLinks(context.Context, *ListMyGarageLinksRequest) (*ListMyGarageLinksResponse, error)
	// Accepts a garage's request to link the user with its customer profile.
	AcceptGarageLink(context.Context, *AcceptGarageLinkRequest) (*AcceptGarageLinkResponse, error)
	DeclineGarageLink(context.Context, *DeclineGarageLinkRequest) (*DeclineGarageLinkResponse, error)
	// Ends a link from the user's side.
	UnlinkGarageLink(context.Context, *UnlinkGarageLinkRequest) (*UnlinkGarageLinkResponse, error)
	// One of the person's vehicles' repair history (FR-CAPP-02, FR-CUS-03);
	// NOT_FOUND unless the vehicle belongs to their customer record there.
	GetMyVehicleHistory(context.Context, *GetMyVehicleHistoryRequest) (*GetMyVehicleHistoryResponse, error)
	mustEmbedUnimplementedCustomerPortalServiceServer()
}

// UnimplementedCustomerPortalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCustomerPortalServiceServer struct{}

func (UnimplementedCustomerPortalServiceServer) ListMyVehicles(context.Context, *ListMyVehiclesRequest) (*ListMyVehiclesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyVehicles not implemented")
}
func (UnimplementedCustomerPortalServiceServer) ListMyGarageLinks(context.Context, *ListMyGarageLinksRequest) (*ListMyGarageLinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyGarageLinks not implemented")
}
func (UnimplementedCustomerPortalServiceServer) AcceptGarageLink(context.Context, *AcceptGarageLinkRequest) (*AcceptGarageLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptGarageLink not implemented")
}
func (UnimplementedCustomerPortalServiceServer) DeclineGarageLink(context.Context, *DeclineGarageLinkRequest) (*DeclineGarageLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeclineGarageLink not implemented")
}
func (UnimplementedCustomerPortalServiceServer) UnlinkGarageLink(context.Context, *UnlinkGarageLinkRequest) (*UnlinkGarageLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlinkGarageLink not implemented")
}
func (UnimplementedCustomerPortalServiceServer) GetMyVehicleHistory(context.Context, *GetMyVehicleHistoryRequest) (*GetMyVehicleHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyVehicleHistory not implemented")
}
func (UnimplementedCustomerPortalServiceServer) mustEmbedUnimplementedCustomerPortalServiceServer() {}
func (UnimplementedCustomerPortalServiceServer) testEmbeddedByValue()                               {}

// UnsafeCustomerPortalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomerPortalServiceServer will
// result in compilation errors.
type UnsafeCustomerPortalServiceServer interface {
	mustEmbedUnimplementedCustomerPortalServiceServer()
}

func RegisterCustomerPortalServiceServer(s grpc.ServiceRegistrar, srv CustomerPortalServiceServer) {
	// If the following call panics, it indicates UnimplementedCustomerPortalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CustomerPortalService_ServiceDesc, srv)
}

func _CustomerPortalService_ListMyVehicles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyVehiclesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerPortalServiceServer).ListMyVehicles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerPortalService_ListMyVehicles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerPortalServiceServer).ListMyVehicles(ctx, req.(*ListMyVehiclesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerPortalService_ListMyGarageLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyGarageLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerPortalServiceServer).ListMyGarageLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerPortalService_ListMyGarageLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerPortalServiceServer).ListMyGarageLinks(ctx, req.(*ListMyGarageLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerPortalService_AcceptGarageLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptGarageLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerPortalServiceServer).AcceptGarageLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerPortalService_AcceptGarageLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerPortalServiceServer).AcceptGarageLink(ctx, req.(*AcceptGarageLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerPortalService_DeclineGarageLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeclineGarageLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerPortalServiceServer).DeclineGarageLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerPortalService_DeclineGarageLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerPortalServiceServer).DeclineGarageLink(ctx, req.(*DeclineGarageLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerPortalService_UnlinkGarageLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlinkGarageLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerPortalServiceServer).UnlinkGarageLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerPortalService_UnlinkGarageLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerPortalServiceServer).UnlinkGarageLink(ctx, req.(*UnlinkGarageLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerPortalService_GetMyVehicleHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyVehicleHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerPortalServiceServer).GetMyVehicleHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerPortalService_GetMyVehicleHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerPortalServiceServer).GetMyVehicleHistory(ctx, req.(*GetMyVehicleHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomerPortalService_ServiceDesc is the grpc.ServiceDesc for CustomerPortalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomerPortalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vietgara.customerportal.v1.CustomerPortalService",
	HandlerType: (*CustomerPortalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMyVehicles",
			Handler:    _CustomerPortalService_ListMyVehicles_Handler,
		},
		{
			MethodName: "ListMyGarageLinks",
			Handler:    _CustomerPortalService_ListMyGarageLinks_Handler,
		},
		{
			MethodName: "AcceptGarageLink",
			Handler:    _CustomerPortalService_AcceptGarageLink_Handler,
		},
		{
			MethodName: "DeclineGarageLink",
			Handler:    _CustomerPortalService_DeclineGarageLink_Handler,
		},
		{
			MethodName: "UnlinkGarageLink",
			Handler:    _CustomerPortalService_UnlinkGarageLink_Handler,
		},
		{
			MethodName: "GetMyVehicleHistory",
			Handler:    _CustomerPortalService_GetMyVehicleHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vietgara/customerportal/v1/customer_portal.proto",
}
