// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vietgara/license/v1/license.proto

// Package vietgara.license.v1 defines the License Management module (HLD
// module #3): subscription plans, the per-garage subscription and its
// entitlements.
// See: FRD FR-LIC-01/02/04, API Specification Section 4, Database Design
// Section 6.3, LLD Section 3.

package licensev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BillingCycle is how often a plan is billed.
type BillingCycle int32

const (
	BillingCycle_BILLING_CYCLE_UNSPECIFIED BillingCycle = 0
	BillingCycle_BILLING_CYCLE_MONTHLY     BillingCycle = 1
	BillingCycle_BILLING_CYCLE_YEARLY      BillingCycle = 2
)

// Enum value maps for BillingCycle.
var (
	BillingCycle_name = map[int32]string{
		0: "BILLING_CYCLE_UNSPECIFIED",
		1: "BILLING_CYCLE_MONTHLY",
		2: "BILLING_CYCLE_YEARLY",
	}
	BillingCycle_value = map[string]int32{
		"BILLING_CYCLE_UNSPECIFIED": 0,
		"BILLING_CYCLE_MONTHLY":     1,
		"BILLING_CYCLE_YEARLY":      2,
	}
)

func (x BillingCycle) Enum() *BillingCycle {
	p := new(BillingCycle)
	*p = x
	return p
}

func (x BillingCycle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BillingCycle) Descriptor() protoreflect.EnumDescriptor {
	return file_vietgara_license_v1_license_proto_enumTypes[0].Descriptor()
}

func (BillingCycle) Type() protoreflect.EnumType {
	return &file_vietgara_license_v1_license_proto_enumTypes[0]
}

func (x BillingCycle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BillingCycle.Descriptor instead.
func (BillingCycle) EnumDescriptor() ([]byte, []int) {
	return file_vietgara_license_v1_license_proto_rawDescGZIP(), []int{0}
}

// SubscriptionStatus is the lifecycle state of a subscription (LLD 3.1).
type SubscriptionStatus int32

const (
	SubscriptionStatus_SUBSCRIPTION_STATUS_UNSPECIFIED SubscriptionStatus = 0
	// Free trial period after the garage was created (FR-LIC-01).
	SubscriptionStatus_SUBSCRIPTION_STATUS_TRIAL SubscriptionStatus = 1
	// Paid and within the current period.
	SubscriptionStatus_SUBSCRIPTION_STATUS_ACTIVE SubscriptionStatus = 2
	// Expired but within the grace period: read-only mode (FR-LIC-04).
	SubscriptionStatus_SUBSCRIPTION_STATUS_PAST_DUE SubscriptionStatus = 3
	// Expired past the grace period: fully locked.
	SubscriptionStatus_SUBSCRIPTION_STATUS_SUSPENDED SubscriptionStatus = 4
	SubscriptionStatus_SUBSCRIPTION_STATUS_CANCELLED SubscriptionStatus = 5
)

// Enum value maps for SubscriptionStatus.
var (
	SubscriptionStatus_name = map[int32]string{
		0: "SUBSCRIPTION_STATUS_UNSPECIFIED",
		1: "SUBSCRIPTION_STATUS_TRIAL",
		2: "SUBSCRIPTION_STATUS_ACTIVE",
		3: "SUBSCRIPTION_STATUS_PAST_DUE",
		4: "SUBSCRIPTION_STATUS_SUSPENDED",
		5: "SUBSCRIPTION_STATUS_CANCELLED",
	}
	SubscriptionStatus_value = map[string]int32{
		"SUBSCRIPTION_STATUS_UNSPECIFIED": 0,
		"SUBSCRIPTION_STATUS_TRIAL":       1,
		"SUBSCRIPTION_STATUS_ACTIVE":      2,
		"SUBSCRIPTION_STATUS_PAST_DUE":    3,
		"SUBSCRIPTION_STATUS_SUSPENDED":   4,
		"SUBSCRIPTION_STATUS_CANCELLED":   5,
	}
)

func (x SubscriptionStatus) Enum() *SubscriptionStatus {
	p := new(SubscriptionStatus)
	*p = x
	return p
}

func (x SubscriptionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_vietgara_license_v1_license_proto_enumTypes[1].Descriptor()
}

func (SubscriptionStatus) Type() protoreflect.EnumType {
	return &file_vietgara_license_v1_license_proto_enumTypes[1]
}

func (x SubscriptionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionStatus.Descriptor instead.
func (SubscriptionStatus) EnumDescriptor() ([]byte, []int) {
	return file_vietgara_license_v1_license_proto_rawDescGZIP(), []int{1}
}

// PlanLimits caps the resources a garage may use under a plan.
type PlanLimits struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum active staff members per garage.
	MaxUsers int32 `protobuf:"varint,1,opt,name=max_users,json=maxUsers,proto3" json:"max_users,omitempty"`
	// Garages (branches) included in the plan.
	MaxGarages    int32 `protobuf:"varint,2,opt,name=max_garages,json=maxGarages,proto3" json:"max_garages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanLimits) Reset() {
	*x = PlanLimits{}
	mi := &file_vietgara_license_v1_license_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanLimits) ProtoMessage() {}

func (x *PlanLimits) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_license_v1_license_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanLimits.ProtoReflect.Descriptor instead.
func (*PlanLimits) Descriptor() ([]byte, []int) {
	return file_vietgara_license_v1_license_proto_rawDescGZIP(), []int{0}
}

func (x *PlanLimits) GetMaxUsers() int32 {
	if x != nil {
		return x.MaxUsers
	}
	return 0
}

func (x *PlanLimits) GetMaxGarages() int32 {
	if x != nil {
		return x.MaxGarages
	}
	return 0
}

// Plan is a subscription plan offered by the platform. Maps to the "plans"
// table (Database Design Section 6.3).
type Plan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Stable machine name, e.g. "starter".
	Code        string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Price per billing cycle, in the smallest unit of currency (VND has
	// no minor unit).
	Price        int64        `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Currency     string       `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	BillingCycle BillingCycle `protobuf:"varint,7,opt,name=billing_cycle,json=billingCycle,proto3,enum=vietgara.license.v1.BillingCycle" json:"billing_cycle,omitempty"`
	Limits       *PlanLimits  `protobuf:"bytes,8,opt,name=limits,proto3" json:"limits,omitempty"`
	// Feature keys the plan enables, e.g. "inventory".
	Features      []string `protobuf:"bytes,9,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_vietgara_license_v1_license_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_license_v1_license_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_vietgara_license_v1_license_proto_rawDescGZIP(), []int{1}
}

func (x *Plan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Plan) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Plan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plan) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Plan) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Plan) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Plan) GetBillingCycle() BillingCycle {
	if x != nil {
		return x.BillingCycle
	}
	return BillingCycle_BILLING_CYCLE_UNSPECIFIED
}

func (x *Plan) GetLimits() *PlanLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *Plan) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

// Subscription is the license of one garage (1 subscription per garage).
// Maps to the "subscriptions" table.
type Subscription struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GarageId string                 `protobuf:"bytes,2,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	Status   SubscriptionStatus     `protobuf:"varint,3,opt,name=status,proto3,enum=vietgara.license.v1.SubscriptionStatus" json:"status,omitempty"`
	Plan     *Plan                  `protobuf:"bytes,4,opt,name=plan,proto3" json:"plan,omitempty"`
	// End of the free trial; unset once the garage has paid.
	TrialEndAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=trial_end_at,json=trialEndAt,proto3" json:"trial_end_at,omitempty"`
	CurrentPeriodStart *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=current_period_start,json=currentPeriodStart,proto3" json:"current_period_start,omitempty"`
	// When the current trial or paid period ends.
	CurrentPeriodEnd *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=current_period_end,json=currentPeriodEnd,proto3" json:"current_period_end,omitempty"`
	// End of the read-only grace period; set once the period has expired.
	GracePeriodEnd *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=grace_period_end,json=gracePeriodEnd,proto3" json:"grace_period_end,omitempty"`
	AutoRenew      bool                   `protobuf:"varint,9,opt,name=auto_renew,json=autoRenew,proto3" json:"auto_renew,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_vietgara_license_v1_license_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_license_v1_license_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_vietgara_license_v1_license_proto_rawDescGZIP(), []int{2}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *Subscription) GetStatus() SubscriptionStatus {
	if x != nil {
		return x.Status
	}
	return SubscriptionStatus_SUBSCRIPTION_STATUS_UNSPECIFIED
}

func (x *Subscription) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *Subscription) GetTrialEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TrialEndAt
	}
	return nil
}

func (x *Subscription) GetCurrentPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.CurrentPeriodStart
	}
	return nil
}

func (x *Subscription) GetCurrentPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.CurrentPeriodEnd
	}
	return nil
}

func (x *Subscription) GetGracePeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.GracePeriodEnd
	}
	return nil
}

func (x *Subscription) GetAutoRenew() bool {
	if x != nil {
		return x.AutoRenew
	}
	return false
}

func (x *Subscription) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Subscription) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Entitlements is what a garage may currently use, derived from its
// subscription and served from the entitlement cache.
type Entitlements struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	GarageId string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	Status   SubscriptionStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=vietgara.license.v1.SubscriptionStatus" json:"status,omitempty"`
	PlanCode string                 `protobuf:"bytes,3,opt,name=plan_code,json=planCode,proto3" json:"plan_code,omitempty"`
	// Enabled feature keys.
	Features []string    `protobuf:"bytes,4,rep,name=features,proto3" json:"features,omitempty"`
	Limits   *PlanLimits `protobuf:"bytes,5,opt,name=limits,proto3" json:"limits,omitempty"`
	// True when writes are blocked (past due or suspended).
	ReadOnly         bool                   `protobuf:"varint,6,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	CurrentPeriodEnd *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=current_period_end,json=currentPeriodEnd,proto3" json:"current_period_end,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Entitlements) Reset() {
	*x = Entitlements{}
	mi := &file_vietgara_license_v1_license_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entitlements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entitlements) ProtoMessage() {}

func (x *Entitlements) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_license_v1_license_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entitlements.ProtoReflect.Descriptor instead.
func (*Entitlements) Descriptor() ([]byte, []int) {
	return file_vietgara_license_v1_license_proto_rawDescGZIP(), []int{3}
}

func (x *Entitlements) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *Entitlements) GetStatus() SubscriptionStatus {
	if x != nil {
		return x.Status
	}
	return SubscriptionStatus_SUBSCRIPTION_STATUS_UNSPECIFIED
}

func (x *Entitlements) GetPlanCode() string {
	if x != nil {
		return x.PlanCode
	}
	return ""
}

func (x *Entitlements) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *Entitlements) GetLimits() *PlanLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *Entitlements) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *Entitlements) GetCurrentPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.CurrentPeriodEnd
	}
	return nil
}

// ListPlansRequest lists the plans a garage can subscribe to.
type ListPlansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansRequest) Reset() {
	*x = ListPlansRequest{}
	mi := &file_vietgara_license_v1_license_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansRequest) ProtoMessage() {}

func (x *ListPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_license_v1_license_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansRequest.ProtoReflect.Descriptor instead.
func (*ListPlansRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_license_v1_license_proto_rawDescGZIP(), []int{4}
}

// ListPlansResponse is the list of public plans, cheapest first.
type ListPlansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*Plan                `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansResponse) Reset() {
	*x = ListPlansResponse{}
	mi := &file_vietgara_license_v1_license_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansResponse) ProtoMessage() {}

func (x *ListPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_license_v1_license_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansResponse.ProtoReflect.Descriptor instead.
func (*ListPlansResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_license_v1_license_proto_rawDescGZIP(), []int{5}
}

func (x *ListPlansResponse) GetPlans() []*Plan {
	if x != nil {
		return x.Plans
	}
	return nil
}

// GetSubscriptionRequest returns the subscription of a garage.
type GetSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GarageId      string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionRequest) Reset() {
	*x = GetSubscriptionRequest{}
	mi := &file_vietgara_license_v1_license_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionRequest) ProtoMessage() {}

func (x *GetSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_license_v1_license_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_license_v1_license_proto_rawDescGZIP(), []int{6}
}

func (x *GetSubscriptionRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

// GetSubscriptionResponse is the response of GetSubscription.
type GetSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionResponse) Reset() {
	*x = GetSubscriptionResponse{}
	mi := &file_vietgara_license_v1_license_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionResponse) ProtoMessage() {}

func (x *GetSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_license_v1_license_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_license_v1_license_proto_rawDescGZIP(), []int{7}
}

func (x *GetSubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

// ChangePlanRequest upgrades, downgrades or renews the subscription of a
// garage (FR-LIC-02).
type ChangePlanRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	GarageId string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	// Target plan; the current plan renews it.
	PlanId        string `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePlanRequest) Reset() {
	*x = ChangePlanRequest{}
	mi := &file_vietgara_license_v1_license_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePlanRequest) ProtoMessage() {}

func (x *ChangePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_license_v1_license_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePlanRequest.ProtoReflect.Descriptor instead.
func (*ChangePlanRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_license_v1_license_proto_rawDescGZIP(), []int{8}
}

func (x *ChangePlanRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *ChangePlanRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

// ChangePlanResponse is the response of ChangePlan.
type ChangePlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePlanResponse) Reset() {
	*x = ChangePlanResponse{}
	mi := &file_vietgara_license_v1_license_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePlanResponse) ProtoMessage() {}

func (x *ChangePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_license_v1_license_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePlanResponse.ProtoReflect.Descriptor instead.
func (*ChangePlanResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_license_v1_license_proto_rawDescGZIP(), []int{9}
}

func (x *ChangePlanResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

// GetEntitlementsRequest returns what a garage may currently use.
type GetEntitlementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GarageId      string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntitlementsRequest) Reset() {
	*x = GetEntitlementsRequest{}
	mi := &file_vietgara_license_v1_license_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntitlementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntitlementsRequest) ProtoMessage() {}

func (x *GetEntitlementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_license_v1_license_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntitlementsRequest.ProtoReflect.Descriptor instead.
func (*GetEntitlementsRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_license_v1_license_proto_rawDescGZIP(), []int{10}
}

func (x *GetEntitlementsRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

// GetEntitlementsResponse is the response of GetEntitlements.
type GetEntitlementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entitlements  *Entitlements          `protobuf:"bytes,1,opt,name=entitlements,proto3" json:"entitlements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntitlementsResponse) Reset() {
	*x = GetEntitlementsResponse{}
	mi := &file_vietgara_license_v1_license_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntitlementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntitlementsResponse) ProtoMessage() {}

func (x *GetEntitlementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_license_v1_license_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntitlementsResponse.ProtoReflect.Descriptor instead.
func (*GetEntitlementsResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_license_v1_license_proto_rawDescGZIP(), []int{11}
}

func (x *GetEntitlementsResponse) GetEntitlements() *Entitlements {
	if x != nil {
		return x.Entitlements
	}
	return nil
}

var File_vietgara_license_v1_license_proto protoreflect.FileDescriptor

const file_vietgara_license_v1_license_proto_rawDesc = "" +
	"\n" +
	"!vietgara/license/v1/license.proto\x12\x13vietgara.license.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"J\n" +
	"\n" +
	"PlanLimits\x12\x1b\n" +
	"\tmax_users\x18\x01 \x01(\x05R\bmaxUsers\x12\x1f\n" +
	"\vmax_garages\x18\x02 \x01(\x05R\n" +
	"maxGarages\"\xaf\x02\n" +
	"\x04Plan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12F\n" +
	"\rbilling_cycle\x18\a \x01(\x0e2!.vietgara.license.v1.BillingCycleR\fbillingCycle\x127\n" +
	"\x06limits\x18\b \x01(\v2\x1f.vietgara.license.v1.PlanLimitsR\x06limits\x12\x1a\n" +
	"\bfeatures\x18\t \x03(\tR\bfeatures\"\xdc\x04\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tgarage_id\x18\x02 \x01(\tR\bgarageId\x12?\n" +
	"\x06status\x18\x03 \x01(\x0e2'.vietgara.license.v1.SubscriptionStatusR\x06status\x12-\n" +
	"\x04plan\x18\x04 \x01(\v2\x19.vietgara.license.v1.PlanR\x04plan\x12<\n" +
	"\ftrial_end_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"trialEndAt\x12L\n" +
	"\x14current_period_start\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x12currentPeriodStart\x12H\n" +
	"\x12current_period_end\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x10currentPeriodEnd\x12D\n" +
	"\x10grace_period_end\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0egracePeriodEnd\x12\x1d\n" +
	"\n" +
	"auto_renew\x18\t \x01(\bR\tautoRenew\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc5\x02\n" +
	"\fEntitlements\x12\x1b\n" +
	"\tgarage_id\x18\x01 \x01(\tR\bgarageId\x12?\n" +
	"\x06status\x18\x02 \x01(\x0e2'.vietgara.license.v1.SubscriptionStatusR\x06status\x12\x1b\n" +
	"\tplan_code\x18\x03 \x01(\tR\bplanCode\x12\x1a\n" +
	"\bfeatures\x18\x04 \x03(\tR\bfeatures\x127\n" +
	"\x06limits\x18\x05 \x01(\v2\x1f.vietgara.license.v1.PlanLimitsR\x06limits\x12\x1b\n" +
	"\tread_only\x18\x06 \x01(\bR\breadOnly\x12H\n" +
	"\x12current_period_end\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x10currentPeriodEnd\"\x12\n" +
	"\x10ListPlansRequest\"D\n" +
	"\x11ListPlansResponse\x12/\n" +
	"\x05plans\x18\x01 \x03(\v2\x19.vietgara.license.v1.PlanR\x05plans\"5\n" +
	"\x16GetSubscriptionRequest\x12\x1b\n" +
	"\tgarage_id\x18\x01 \x01(\tR\bgarageId\"`\n" +
	"\x17GetSubscriptionResponse\x12E\n" +
	"\fsubscription\x18\x01 \x01(\v2!.vietgara.license.v1.SubscriptionR\fsubscription\"I\n" +
	"\x11ChangePlanRequest\x12\x1b\n" +
	"\tgarage_id\x18\x01 \x01(\tR\bgarageId\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\"[\n" +
	"\x12ChangePlanResponse\x12E\n" +
	"\fsubscription\x18\x01 \x01(\v2!.vietgara.license.v1.SubscriptionR\fsubscription\"5\n" +
	"\x16GetEntitlementsRequest\x12\x1b\n" +
	"\tgarage_id\x18\x01 \x01(\tR\bgarageId\"`\n" +
	"\x17GetEntitlementsResponse\x12E\n" +
	"\fentitlements\x18\x01 \x01(\v2!.vietgara.license.v1.EntitlementsR\fentitlements*b\n" +
	"\fBillingCycle\x12\x1d\n" +
	"\x19BILLING_CYCLE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15BILLING_CYCLE_MONTHLY\x10\x01\x12\x18\n" +
	"\x14BILLING_CYCLE_YEARLY\x10\x02*\xe0\x01\n" +
	"\x12SubscriptionStatus\x12#\n" +
	"\x1fSUBSCRIPTION_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19SUBSCRIPTION_STATUS_TRIAL\x10\x01\x12\x1e\n" +
	"\x1aSUBSCRIPTION_STATUS_ACTIVE\x10\x02\x12 \n" +
	"\x1cSUBSCRIPTION_STATUS_PAST_DUE\x10\x03\x12!\n" +
	"\x1dSUBSCRIPTION_STATUS_SUSPENDED\x10\x04\x12!\n" +
	"\x1dSUBSCRIPTION_STATUS_CANCELLED\x10\x052\xa7\x03\n" +
	"\x0eLicenseService\x12Z\n" +
	"\tListPlans\x12%.vietgara.license.v1.ListPlansRequest\x1a&.vietgara.license.v1.ListPlansResponse\x12l\n" +
	"\x0fGetSubscription\x12+.vietgara.license.v1.GetSubscriptionRequest\x1a,.vietgara.license.v1.GetSubscriptionResponse\x12]\n" +
	"\n" +
	"ChangePlan\x12&.vietgara.license.v1.ChangePlanRequest\x1a'.vietgara.license.v1.ChangePlanResponse\x12l\n" +
	"\x0fGetEntitlements\x12+.vietgara.license.v1.GetEntitlementsRequest\x1a,.vietgara.license.v1.GetEntitlementsResponseBLZJgithub.com/viettechno/vietgara-proto/apis-go/vietgara/license/v1;licensev1b\x06proto3"

var (
	file_vietgara_license_v1_license_proto_rawDescOnce sync.Once
	file_vietgara_license_v1_license_proto_rawDescData []byte
)

func file_vietgara_license_v1_license_proto_rawDescGZIP() []byte {
	file_vietgara_license_v1_license_proto_rawDescOnce.Do(func() {
		file_vietgara_license_v1_license_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vietgara_license_v1_license_proto_rawDesc), len(file_vietgara_license_v1_license_proto_rawDesc)))
	})
	return file_vietgara_license_v1_license_proto_rawDescData
}

var file_vietgara_license_v1_license_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_vietgara_license_v1_license_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_vietgara_license_v1_license_proto_goTypes = []any{
	(BillingCycle)(0),               // 0: vietgara.license.v1.BillingCycle
	(SubscriptionStatus)(0),         // 1: vietgara.license.v1.SubscriptionStatus
	(*PlanLimits)(nil),              // 2: vietgara.license.v1.PlanLimits
	(*Plan)(nil),                    // 3: vietgara.license.v1.Plan
	(*Subscription)(nil),            // 4: vietgara.license.v1.Subscription
	(*Entitlements)(nil),            // 5: vietgara.license.v1.Entitlements
	(*ListPlansRequest)(nil),        // 6: vietgara.license.v1.ListPlansRequest
	(*ListPlansResponse)(nil),       // 7: vietgara.license.v1.ListPlansResponse
	(*GetSubscriptionRequest)(nil),  // 8: vietgara.license.v1.GetSubscriptionRequest
	(*GetSubscriptionResponse)(nil), // 9: vietgara.license.v1.GetSubscriptionResponse
	(*ChangePlanRequest)(nil),       // 10: vietgara.license.v1.ChangePlanRequest
	(*ChangePlanResponse)(nil),      // 11: vietgara.license.v1.ChangePlanResponse
	(*GetEntitlementsRequest)(nil),  // 12: vietgara.license.v1.GetEntitlementsRequest
	(*GetEntitlementsResponse)(nil), // 13: vietgara.license.v1.GetEntitlementsResponse
	(*timestamppb.Timestamp)(nil),   // 14: google.protobuf.Timestamp
}
var file_vietgara_license_v1_license_proto_depIdxs = []int32{
	0,  // 0: vietgara.license.v1.Plan.billing_cycle:type_name -> vietgara.license.v1.BillingCycle
	2,  // 1: vietgara.license.v1.Plan.limits:type_name -> vietgara.license.v1.PlanLimits
	1,  // 2: vietgara.license.v1.Subscription.status:type_name -> vietgara.license.v1.SubscriptionStatus
	3,  // 3: vietgara.license.v1.Subscription.plan:type_name -> vietgara.license.v1.Plan
	14, // 4: vietgara.license.v1.Subscription.trial_end_at:type_name -> google.protobuf.Timestamp
	14, // 5: vietgara.license.v1.Subscription.current_period_start:type_name -> google.protobuf.Timestamp
	14, // 6: vietgara.license.v1.Subscription.current_period_end:type_name -> google.protobuf.Timestamp
	14, // 7: vietgara.license.v1.Subscription.grace_period_end:type_name -> google.protobuf.Timestamp
	14, // 8: vietgara.license.v1.Subscription.created_at:type_name -> google.protobuf.Timestamp
	14, // 9: vietgara.license.v1.Subscription.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 10: vietgara.license.v1.Entitlements.status:type_name -> vietgara.license.v1.SubscriptionStatus
	2,  // 11: vietgara.license.v1.Entitlements.limits:type_name -> vietgara.license.v1.PlanLimits
	14, // 12: vietgara.license.v1.Entitlements.current_period_end:type_name -> google.protobuf.Timestamp
	3,  // 13: vietgara.license.v1.ListPlansResponse.plans:type_name -> vietgara.license.v1.Plan
	4,  // 14: vietgara.license.v1.GetSubscriptionResponse.subscription:type_name -> vietgara.license.v1.Subscription
	4,  // 15: vietgara.license.v1.ChangePlanResponse.subscription:type_name -> vietgara.license.v1.Subscription
	5,  // 16: vietgara.license.v1.GetEntitlementsResponse.entitlements:type_name -> vietgara.license.v1.Entitlements
	6,  // 17: vietgara.license.v1.LicenseService.ListPlans:input_type -> vietgara.license.v1.ListPlansRequest
	8,  // 18: vietgara.license.v1.LicenseService.GetSubscription:input_type -> vietgara.license.v1.GetSubscriptionRequest
	10, // 19: vietgara.license.v1.LicenseService.ChangePlan:input_type -> vietgara.license.v1.ChangePlanRequest
	12, // 20: vietgara.license.v1.LicenseService.GetEntitlements:input_type -> vietgara.license.v1.GetEntitlementsRequest
	7,  // 21: vietgara.license.v1.LicenseService.ListPlans:output_type -> vietgara.license.v1.ListPlansResponse
	9,  // 22: vietgara.license.v1.LicenseService.GetSubscription:output_type -> vietgara.license.v1.GetSubscriptionResponse
	11, // 23: vietgara.license.v1.LicenseService.ChangePlan:output_type -> vietgara.license.v1.ChangePlanResponse
	13, // 24: vietgara.license.v1.LicenseService.GetEntitlements:output_type -> vietgara.license.v1.GetEntitlementsResponse
	21, // [21:25] is the sub-list for method output_type
	17, // [17:21] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_vietgara_license_v1_license_proto_init() }
func file_vietgara_license_v1_license_proto_init() {
	if File_vietgara_license_v1_license_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vietgara_license_v1_license_proto_rawDesc), len(file_vietgara_license_v1_license_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vietgara_license_v1_license_proto_goTypes,
		DependencyIndexes: file_vietgara_license_v1_license_proto_depIdxs,
		EnumInfos:         file_vietgara_license_v1_license_proto_enumTypes,
		MessageInfos:      file_vietgara_license_v1_license_proto_msgTypes,
	}.Build()
	File_vietgara_license_v1_license_proto = out.File
	file_vietgara_license_v1_license_proto_goTypes = nil
	file_vietgara_license_v1_license_proto_depIdxs = nil
}
