// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: vietgara/customer/v1/customer_link.proto

package customerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CustomerLinkService_RequestCustomerUserLink_FullMethodName = "/vietgara.customer.v1.CustomerLinkService/RequestCustomerUserLink"
	CustomerLinkService_ConfirmCustomerUserLink_FullMethodName = "/vietgara.customer.v1.CustomerLinkService/ConfirmCustomerUserLink"
	CustomerLinkService_UnlinkCustomerUser_FullMethodName      = "/vietgara.customer.v1.CustomerLinkService/UnlinkCustomerUser"
)

// CustomerLinkServiceClient is the client API for CustomerLinkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CustomerLinkService links a garage's customer profile with a VietGara
// user, with the user's consent (FR-CUS-06). Suppliers use their own link
// in Phase 17. Needs PERMISSION_CUSTOMER_WRITE.
type CustomerLinkServiceClient interface {
	// Asks the user that owns the profile's verified phone or e-mail to
	// confirm; sends them a one-time code and a request in the app. Fails
	// FAILED_PRECONDITION when no user matches.
	RequestCustomerUserLink(ctx context.Context, in *RequestCustomerUserLinkRequest, opts ...grpc.CallOption) (*RequestCustomerUserLinkResponse, error)
	// Confirms the pending request with the code the user read out.
	ConfirmCustomerUserLink(ctx context.Context, in *ConfirmCustomerUserLinkRequest, opts ...grpc.CallOption) (*ConfirmCustomerUserLinkResponse, error)
	// Ends the link from the garage's side; the profile stays.
	UnlinkCustomerUser(ctx context.Context, in *UnlinkCustomerUserRequest, opts ...grpc.CallOption) (*UnlinkCustomerUserResponse, error)
}

type customerLinkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomerLinkServiceClient(cc grpc.ClientConnInterface) CustomerLinkServiceClient {
	return &customerLinkServiceClient{cc}
}

func (c *customerLinkServiceClient) RequestCustomerUserLink(ctx context.Context, in *RequestCustomerUserLinkRequest, opts ...grpc.CallOption) (*RequestCustomerUserLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestCustomerUserLinkResponse)
	err := c.cc.Invoke(ctx, CustomerLinkService_RequestCustomerUserLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerLinkServiceClient) ConfirmCustomerUserLink(ctx context.Context, in *ConfirmCustomerUserLinkRequest, opts ...grpc.CallOption) (*ConfirmCustomerUserLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmCustomerUserLinkResponse)
	err := c.cc.Invoke(ctx, CustomerLinkService_ConfirmCustomerUserLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerLinkServiceClient) UnlinkCustomerUser(ctx context.Context, in *UnlinkCustomerUserRequest, opts ...grpc.CallOption) (*UnlinkCustomerUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlinkCustomerUserResponse)
	err := c.cc.Invoke(ctx, CustomerLinkService_UnlinkCustomerUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerLinkServiceServer is the server API for CustomerLinkService service.
// All implementations must embed UnimplementedCustomerLinkServiceServer
// for forward compatibility.
//
// CustomerLinkService links a garage's customer profile with a VietGara
// user, with the user's consent (FR-CUS-06). Suppliers use their own link
// in Phase 17. Needs PERMISSION_CUSTOMER_WRITE.
type CustomerLinkServiceServer interface {
	// Asks the user that owns the profile's verified phone or e-mail to
	// confirm; sends them a one-time code and a request in the app. Fails
	// FAILED_PRECONDITION when no user matches.
	RequestCustomerUserLink(context.Context, *RequestCustomerUserLinkRequest) (*RequestCustomerUserLinkResponse, error)
	// Confirms the pending request with the code the user read out.
	ConfirmCustomerUserLink(context.Context, *ConfirmCustomerUserLinkRequest) (*ConfirmCustomerUserLinkResponse, error)
	// Ends the link from the garage's side; the profile stays.
	UnlinkCustomerUser(context.Context, *UnlinkCustomerUserRequest) (*UnlinkCustomerUserResponse, error)
	mustEmbedUnimplementedCustomerLinkServiceServer()
}

// UnimplementedCustomerLinkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCustomerLinkServiceServer struct{}

func (UnimplementedCustomerLinkServiceServer) RequestCustomerUserLink(context.Context, *RequestCustomerUserLinkRequest) (*RequestCustomerUserLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestCustomerUserLink not implemented")
}
func (UnimplementedCustomerLinkServiceServer) ConfirmCustomerUserLink(context.Context, *ConfirmCustomerUserLinkRequest) (*ConfirmCustomerUserLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmCustomerUserLink not implemented")
}
func (UnimplementedCustomerLinkServiceServer) UnlinkCustomerUser(context.Context, *UnlinkCustomerUserRequest) (*UnlinkCustomerUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlinkCustomerUser not implemented")
}
func (UnimplementedCustomerLinkServiceServer) mustEmbedUnimplementedCustomerLinkServiceServer() {}
func (UnimplementedCustomerLinkServiceServer) testEmbeddedByValue()                             {}

// UnsafeCustomerLinkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomerLinkServiceServer will
// result in compilation errors.
type UnsafeCustomerLinkServiceServer interface {
	mustEmbedUnimplementedCustomerLinkServiceServer()
}

func RegisterCustomerLinkServiceServer(s grpc.ServiceRegistrar, srv CustomerLinkServiceServer) {
	// If the following call panics, it indicates UnimplementedCustomerLinkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CustomerLinkService_ServiceDesc, srv)
}

func _CustomerLinkService_RequestCustomerUserLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCustomerUserLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerLinkServiceServer).RequestCustomerUserLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerLinkService_RequestCustomerUserLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerLinkServiceServer).RequestCustomerUserLink(ctx, req.(*RequestCustomerUserLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerLinkService_ConfirmCustomerUserLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmCustomerUserLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerLinkServiceServer).ConfirmCustomerUserLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerLinkService_ConfirmCustomerUserLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerLinkServiceServer).ConfirmCustomerUserLink(ctx, req.(*ConfirmCustomerUserLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerLinkService_UnlinkCustomerUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlinkCustomerUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerLinkServiceServer).UnlinkCustomerUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerLinkService_UnlinkCustomerUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerLinkServiceServer).UnlinkCustomerUser(ctx, req.(*UnlinkCustomerUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomerLinkService_ServiceDesc is the grpc.ServiceDesc for CustomerLinkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomerLinkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vietgara.customer.v1.CustomerLinkService",
	HandlerType: (*CustomerLinkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestCustomerUserLink",
			Handler:    _CustomerLinkService_RequestCustomerUserLink_Handler,
		},
		{
			MethodName: "ConfirmCustomerUserLink",
			Handler:    _CustomerLinkService_ConfirmCustomerUserLink_Handler,
		},
		{
			MethodName: "UnlinkCustomerUser",
			Handler:    _CustomerLinkService_UnlinkCustomerUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vietgara/customer/v1/customer_link.proto",
}
