// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: vietgara/customer/v1/customer_link.proto

/*
Package customerv1 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package customerv1

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var (
	_ codes.Code
	_ io.Reader
	_ status.Status
	_ = errors.New
	_ = runtime.String
	_ = utilities.NewDoubleArray
	_ = metadata.Join
)

func request_CustomerLinkService_RequestCustomerUserLink_0(ctx context.Context, marshaler runtime.Marshaler, client CustomerLinkServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq RequestCustomerUserLinkRequest
		metadata runtime.ServerMetadata
		err      error
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	val, ok := pathParams["garage_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "garage_id")
	}
	protoReq.GarageId, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "garage_id", err)
	}
	val, ok = pathParams["customer_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "customer_id")
	}
	protoReq.CustomerId, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "customer_id", err)
	}
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	msg, err := client.RequestCustomerUserLink(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_CustomerLinkService_RequestCustomerUserLink_0(ctx context.Context, marshaler runtime.Marshaler, server CustomerLinkServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq RequestCustomerUserLinkRequest
		metadata runtime.ServerMetadata
		err      error
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	val, ok := pathParams["garage_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "garage_id")
	}
	protoReq.GarageId, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "garage_id", err)
	}
	val, ok = pathParams["customer_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "customer_id")
	}
	protoReq.CustomerId, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "customer_id", err)
	}
	msg, err := server.RequestCustomerUserLink(ctx, &protoReq)
	return msg, metadata, err
}

func request_CustomerLinkService_ConfirmCustomerUserLink_0(ctx context.Context, marshaler runtime.Marshaler, client CustomerLinkServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq ConfirmCustomerUserLinkRequest
		metadata runtime.ServerMetadata
		err      error
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	val, ok := pathParams["garage_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "garage_id")
	}
	protoReq.GarageId, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "garage_id", err)
	}
	val, ok = pathParams["customer_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "customer_id")
	}
	protoReq.CustomerId, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "customer_id", err)
	}
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	msg, err := client.ConfirmCustomerUserLink(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_CustomerLinkService_ConfirmCustomerUserLink_0(ctx context.Context, marshaler runtime.Marshaler, server CustomerLinkServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq ConfirmCustomerUserLinkRequest
		metadata runtime.ServerMetadata
		err      error
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	val, ok := pathParams["garage_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "garage_id")
	}
	protoReq.GarageId, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "garage_id", err)
	}
	val, ok = pathParams["customer_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "customer_id")
	}
	protoReq.CustomerId, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "customer_id", err)
	}
	msg, err := server.ConfirmCustomerUserLink(ctx, &protoReq)
	return msg, metadata, err
}

func request_CustomerLinkService_UnlinkCustomerUser_0(ctx context.Context, marshaler runtime.Marshaler, client CustomerLinkServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq UnlinkCustomerUserRequest
		metadata runtime.ServerMetadata
		err      error
	)
	val, ok := pathParams["garage_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "garage_id")
	}
	protoReq.GarageId, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "garage_id", err)
	}
	val, ok = pathParams["customer_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "customer_id")
	}
	protoReq.CustomerId, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "customer_id", err)
	}
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	msg, err := client.UnlinkCustomerUser(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_CustomerLinkService_UnlinkCustomerUser_0(ctx context.Context, marshaler runtime.Marshaler, server CustomerLinkServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq UnlinkCustomerUserRequest
		metadata runtime.ServerMetadata
		err      error
	)
	val, ok := pathParams["garage_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "garage_id")
	}
	protoReq.GarageId, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "garage_id", err)
	}
	val, ok = pathParams["customer_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "customer_id")
	}
	protoReq.CustomerId, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "customer_id", err)
	}
	msg, err := server.UnlinkCustomerUser(ctx, &protoReq)
	return msg, metadata, err
}

// RegisterCustomerLinkServiceHandlerServer registers the http handlers for service CustomerLinkService to "mux".
// UnaryRPC     :call CustomerLinkServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterCustomerLinkServiceHandlerFromEndpoint instead.
// GRPC interceptors will not work for this type of registration. To use interceptors, you must use the "runtime.WithMiddlewares" option in the "runtime.NewServeMux" call.
func RegisterCustomerLinkServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server CustomerLinkServiceServer) error {
	mux.Handle(http.MethodPost, pattern_CustomerLinkService_RequestCustomerUserLink_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/vietgara.customer.v1.CustomerLinkService/RequestCustomerUserLink", runtime.WithHTTPPathPattern("/api/v1/garages/{garage_id}/customers/{customer_id}/user-links"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_CustomerLinkService_RequestCustomerUserLink_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_CustomerLinkService_RequestCustomerUserLink_0(annotatedContext, mux, outboundMarshaler, w, req, response_CustomerLinkService_RequestCustomerUserLink_0{resp.(*RequestCustomerUserLinkResponse)}, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodPost, pattern_CustomerLinkService_ConfirmCustomerUserLink_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/vietgara.customer.v1.CustomerLinkService/ConfirmCustomerUserLink", runtime.WithHTTPPathPattern("/api/v1/garages/{garage_id}/customers/{customer_id}/user-links/current:confirm"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_CustomerLinkService_ConfirmCustomerUserLink_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_CustomerLinkService_ConfirmCustomerUserLink_0(annotatedContext, mux, outboundMarshaler, w, req, response_CustomerLinkService_ConfirmCustomerUserLink_0{resp.(*ConfirmCustomerUserLinkResponse)}, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodDelete, pattern_CustomerLinkService_UnlinkCustomerUser_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/vietgara.customer.v1.CustomerLinkService/UnlinkCustomerUser", runtime.WithHTTPPathPattern("/api/v1/garages/{garage_id}/customers/{customer_id}/user-links/current"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_CustomerLinkService_UnlinkCustomerUser_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_CustomerLinkService_UnlinkCustomerUser_0(annotatedContext, mux, outboundMarshaler, w, req, response_CustomerLinkService_UnlinkCustomerUser_0{resp.(*UnlinkCustomerUserResponse)}, mux.GetForwardResponseOptions()...)
	})

	return nil
}

// RegisterCustomerLinkServiceHandlerFromEndpoint is same as RegisterCustomerLinkServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterCustomerLinkServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.NewClient(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()
	return RegisterCustomerLinkServiceHandler(ctx, mux, conn)
}

// RegisterCustomerLinkServiceHandler registers the http handlers for service CustomerLinkService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterCustomerLinkServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterCustomerLinkServiceHandlerClient(ctx, mux, NewCustomerLinkServiceClient(conn))
}

// RegisterCustomerLinkServiceHandlerClient registers the http handlers for service CustomerLinkService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "CustomerLinkServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "CustomerLinkServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "CustomerLinkServiceClient" to call the correct interceptors. This client ignores the HTTP middlewares.
func RegisterCustomerLinkServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client CustomerLinkServiceClient) error {
	mux.Handle(http.MethodPost, pattern_CustomerLinkService_RequestCustomerUserLink_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/vietgara.customer.v1.CustomerLinkService/RequestCustomerUserLink", runtime.WithHTTPPathPattern("/api/v1/garages/{garage_id}/customers/{customer_id}/user-links"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_CustomerLinkService_RequestCustomerUserLink_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_CustomerLinkService_RequestCustomerUserLink_0(annotatedContext, mux, outboundMarshaler, w, req, response_CustomerLinkService_RequestCustomerUserLink_0{resp.(*RequestCustomerUserLinkResponse)}, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodPost, pattern_CustomerLinkService_ConfirmCustomerUserLink_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/vietgara.customer.v1.CustomerLinkService/ConfirmCustomerUserLink", runtime.WithHTTPPathPattern("/api/v1/garages/{garage_id}/customers/{customer_id}/user-links/current:confirm"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_CustomerLinkService_ConfirmCustomerUserLink_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_CustomerLinkService_ConfirmCustomerUserLink_0(annotatedContext, mux, outboundMarshaler, w, req, response_CustomerLinkService_ConfirmCustomerUserLink_0{resp.(*ConfirmCustomerUserLinkResponse)}, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodDelete, pattern_CustomerLinkService_UnlinkCustomerUser_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/vietgara.customer.v1.CustomerLinkService/UnlinkCustomerUser", runtime.WithHTTPPathPattern("/api/v1/garages/{garage_id}/customers/{customer_id}/user-links/current"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_CustomerLinkService_UnlinkCustomerUser_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_CustomerLinkService_UnlinkCustomerUser_0(annotatedContext, mux, outboundMarshaler, w, req, response_CustomerLinkService_UnlinkCustomerUser_0{resp.(*UnlinkCustomerUserResponse)}, mux.GetForwardResponseOptions()...)
	})
	return nil
}

type response_CustomerLinkService_RequestCustomerUserLink_0 struct {
	*RequestCustomerUserLinkResponse
}

func (m response_CustomerLinkService_RequestCustomerUserLink_0) XXX_ResponseBody() interface{} {
	response := m.RequestCustomerUserLinkResponse
	return response.Link
}

type response_CustomerLinkService_ConfirmCustomerUserLink_0 struct {
	*ConfirmCustomerUserLinkResponse
}

func (m response_CustomerLinkService_ConfirmCustomerUserLink_0) XXX_ResponseBody() interface{} {
	response := m.ConfirmCustomerUserLinkResponse
	return response.Link
}

type response_CustomerLinkService_UnlinkCustomerUser_0 struct {
	*UnlinkCustomerUserResponse
}

func (m response_CustomerLinkService_UnlinkCustomerUser_0) XXX_ResponseBody() interface{} {
	response := m.UnlinkCustomerUserResponse
	return response.Link
}

var (
	pattern_CustomerLinkService_RequestCustomerUserLink_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3, 2, 4, 1, 0, 4, 1, 5, 5, 2, 6}, []string{"api", "v1", "garages", "garage_id", "customers", "customer_id", "user-links"}, ""))
	pattern_CustomerLinkService_ConfirmCustomerUserLink_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3, 2, 4, 1, 0, 4, 1, 5, 5, 2, 6, 2, 7}, []string{"api", "v1", "garages", "garage_id", "customers", "customer_id", "user-links", "current"}, "confirm"))
	pattern_CustomerLinkService_UnlinkCustomerUser_0      = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3, 2, 4, 1, 0, 4, 1, 5, 5, 2, 6, 2, 7}, []string{"api", "v1", "garages", "garage_id", "customers", "customer_id", "user-links", "current"}, ""))
)

var (
	forward_CustomerLinkService_RequestCustomerUserLink_0 = runtime.ForwardResponseMessage
	forward_CustomerLinkService_ConfirmCustomerUserLink_0 = runtime.ForwardResponseMessage
	forward_CustomerLinkService_UnlinkCustomerUser_0      = runtime.ForwardResponseMessage
)
