// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vietgara/customer/v1/customer.proto

package customerv1

import (
	v1 "github.com/viettechno/vietgara-proto/apis-go/vietgara/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CustomerUserLinkStatus is the state of the link between a garage's
// customer profile and a VietGara user (FR-CUS-06). A customer needs no
// user; UNSPECIFIED means the profile has never been linked.
type CustomerUserLinkStatus int32

const (
	CustomerUserLinkStatus_CUSTOMER_USER_LINK_STATUS_UNSPECIFIED CustomerUserLinkStatus = 0
	// The garage asked; the user has not answered yet.
	CustomerUserLinkStatus_CUSTOMER_USER_LINK_STATUS_REQUESTED CustomerUserLinkStatus = 1
	CustomerUserLinkStatus_CUSTOMER_USER_LINK_STATUS_LINKED    CustomerUserLinkStatus = 2
	CustomerUserLinkStatus_CUSTOMER_USER_LINK_STATUS_DECLINED  CustomerUserLinkStatus = 3
	// Ended by either side.
	CustomerUserLinkStatus_CUSTOMER_USER_LINK_STATUS_UNLINKED CustomerUserLinkStatus = 4
)

// Enum value maps for CustomerUserLinkStatus.
var (
	CustomerUserLinkStatus_name = map[int32]string{
		0: "CUSTOMER_USER_LINK_STATUS_UNSPECIFIED",
		1: "CUSTOMER_USER_LINK_STATUS_REQUESTED",
		2: "CUSTOMER_USER_LINK_STATUS_LINKED",
		3: "CUSTOMER_USER_LINK_STATUS_DECLINED",
		4: "CUSTOMER_USER_LINK_STATUS_UNLINKED",
	}
	CustomerUserLinkStatus_value = map[string]int32{
		"CUSTOMER_USER_LINK_STATUS_UNSPECIFIED": 0,
		"CUSTOMER_USER_LINK_STATUS_REQUESTED":   1,
		"CUSTOMER_USER_LINK_STATUS_LINKED":      2,
		"CUSTOMER_USER_LINK_STATUS_DECLINED":    3,
		"CUSTOMER_USER_LINK_STATUS_UNLINKED":    4,
	}
)

func (x CustomerUserLinkStatus) Enum() *CustomerUserLinkStatus {
	p := new(CustomerUserLinkStatus)
	*p = x
	return p
}

func (x CustomerUserLinkStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CustomerUserLinkStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_vietgara_customer_v1_customer_proto_enumTypes[0].Descriptor()
}

func (CustomerUserLinkStatus) Type() protoreflect.EnumType {
	return &file_vietgara_customer_v1_customer_proto_enumTypes[0]
}

func (x CustomerUserLinkStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CustomerUserLinkStatus.Descriptor instead.
func (CustomerUserLinkStatus) EnumDescriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_customer_proto_rawDescGZIP(), []int{0}
}

// Customer is a vehicle owner served by one garage (FR-CUS-01). It needs no
// VietGara user: a walk-in customer is just a profile the garage keeps.
type Customer struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GarageId string                 `protobuf:"bytes,2,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	FullName string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	// Unique per garage among live customers; stored normalized.
	Phone   *string `protobuf:"bytes,4,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Email   *string `protobuf:"bytes,5,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Address *string `protobuf:"bytes,6,opt,name=address,proto3,oneof" json:"address,omitempty"`
	// Personal-data consent (Decree 13/2023/ND-CP); every change is logged.
	PersonalDataConsent   bool                   `protobuf:"varint,7,opt,name=personal_data_consent,json=personalDataConsent,proto3" json:"personal_data_consent,omitempty"`
	PersonalDataConsentAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=personal_data_consent_at,json=personalDataConsentAt,proto3" json:"personal_data_consent_at,omitempty"`
	VehicleCount          int32                  `protobuf:"varint,9,opt,name=vehicle_count,json=vehicleCount,proto3" json:"vehicle_count,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// False once the customer was deactivated instead of deleted (FR-CAT-07);
	// an inactive customer is left out of pickers.
	IsActive bool `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// The state of the link with a user, UNSPECIFIED when never linked.
	LinkStatus    CustomerUserLinkStatus `protobuf:"varint,13,opt,name=link_status,json=linkStatus,proto3,enum=vietgara.customer.v1.CustomerUserLinkStatus" json:"link_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_customer_proto_rawDescGZIP(), []int{0}
}

func (x *Customer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Customer) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *Customer) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Customer) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *Customer) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *Customer) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *Customer) GetPersonalDataConsent() bool {
	if x != nil {
		return x.PersonalDataConsent
	}
	return false
}

func (x *Customer) GetPersonalDataConsentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PersonalDataConsentAt
	}
	return nil
}

func (x *Customer) GetVehicleCount() int32 {
	if x != nil {
		return x.VehicleCount
	}
	return 0
}

func (x *Customer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Customer) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Customer) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Customer) GetLinkStatus() CustomerUserLinkStatus {
	if x != nil {
		return x.LinkStatus
	}
	return CustomerUserLinkStatus_CUSTOMER_USER_LINK_STATUS_UNSPECIFIED
}

type CreateCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GarageId      string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	Customer      *Customer              `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerRequest) Reset() {
	*x = CreateCustomerRequest{}
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerRequest) ProtoMessage() {}

func (x *CreateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerRequest.ProtoReflect.Descriptor instead.
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_customer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCustomerRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *CreateCustomerRequest) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type CreateCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerResponse) Reset() {
	*x = CreateCustomerResponse{}
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerResponse) ProtoMessage() {}

func (x *CreateCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerResponse.ProtoReflect.Descriptor instead.
func (*CreateCustomerResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_customer_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type GetCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GarageId      string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerRequest) Reset() {
	*x = GetCustomerRequest{}
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerRequest) ProtoMessage() {}

func (x *GetCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_customer_proto_rawDescGZIP(), []int{3}
}

func (x *GetCustomerRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *GetCustomerRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type GetCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerResponse) Reset() {
	*x = GetCustomerResponse{}
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerResponse) ProtoMessage() {}

func (x *GetCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_customer_proto_rawDescGZIP(), []int{4}
}

func (x *GetCustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type UpdateCustomerRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	GarageId   string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	CustomerId string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Customer   *Customer              `protobuf:"bytes,3,opt,name=customer,proto3" json:"customer,omitempty"`
	// Filled from the JSON body keys when omitted.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCustomerRequest) Reset() {
	*x = UpdateCustomerRequest{}
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomerRequest) ProtoMessage() {}

func (x *UpdateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomerRequest.ProtoReflect.Descriptor instead.
func (*UpdateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_customer_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCustomerRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *UpdateCustomerRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *UpdateCustomerRequest) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *UpdateCustomerRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCustomerResponse) Reset() {
	*x = UpdateCustomerResponse{}
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomerResponse) ProtoMessage() {}

func (x *UpdateCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomerResponse.ProtoReflect.Descriptor instead.
func (*UpdateCustomerResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_customer_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type ListCustomersRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	GarageId string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	// Fuzzy match on name, phone or e-mail.
	Query    string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Page     int32  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Also list deactivated customers (staff screens); pickers leave it off.
	IncludeInactive bool `protobuf:"varint,5,opt,name=include_inactive,json=includeInactive,proto3" json:"include_inactive,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListCustomersRequest) Reset() {
	*x = ListCustomersRequest{}
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomersRequest) ProtoMessage() {}

func (x *ListCustomersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomersRequest.ProtoReflect.Descriptor instead.
func (*ListCustomersRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_customer_proto_rawDescGZIP(), []int{7}
}

func (x *ListCustomersRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *ListCustomersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListCustomersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCustomersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCustomersRequest) GetIncludeInactive() bool {
	if x != nil {
		return x.IncludeInactive
	}
	return false
}

type ListCustomersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Customer            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *v1.Pagination         `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomersResponse) Reset() {
	*x = ListCustomersResponse{}
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomersResponse) ProtoMessage() {}

func (x *ListCustomersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomersResponse.ProtoReflect.Descriptor instead.
func (*ListCustomersResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_customer_proto_rawDescGZIP(), []int{8}
}

func (x *ListCustomersResponse) GetData() []*Customer {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListCustomersResponse) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type DeleteCustomerRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	GarageId   string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	CustomerId string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Answer the outcome without changing anything (`?dryRun=true`).
	DryRun        bool `protobuf:"varint,3,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCustomerRequest) Reset() {
	*x = DeleteCustomerRequest{}
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCustomerRequest) ProtoMessage() {}

func (x *DeleteCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCustomerRequest.ProtoReflect.Descriptor instead.
func (*DeleteCustomerRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_customer_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCustomerRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *DeleteCustomerRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *DeleteCustomerRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type DeleteCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outcome       v1.DeleteOutcome       `protobuf:"varint,1,opt,name=outcome,proto3,enum=vietgara.common.v1.DeleteOutcome" json:"outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCustomerResponse) Reset() {
	*x = DeleteCustomerResponse{}
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCustomerResponse) ProtoMessage() {}

func (x *DeleteCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCustomerResponse.ProtoReflect.Descriptor instead.
func (*DeleteCustomerResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_customer_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCustomerResponse) GetOutcome() v1.DeleteOutcome {
	if x != nil {
		return x.Outcome
	}
	return v1.DeleteOutcome(0)
}

type ActivateCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GarageId      string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateCustomerRequest) Reset() {
	*x = ActivateCustomerRequest{}
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateCustomerRequest) ProtoMessage() {}

func (x *ActivateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateCustomerRequest.ProtoReflect.Descriptor instead.
func (*ActivateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_customer_proto_rawDescGZIP(), []int{11}
}

func (x *ActivateCustomerRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *ActivateCustomerRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type ActivateCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateCustomerResponse) Reset() {
	*x = ActivateCustomerResponse{}
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateCustomerResponse) ProtoMessage() {}

func (x *ActivateCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateCustomerResponse.ProtoReflect.Descriptor instead.
func (*ActivateCustomerResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_customer_proto_rawDescGZIP(), []int{12}
}

func (x *ActivateCustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type LookupCustomersRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	GarageId string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	// Either or both; the garage's customers matching any of them are listed.
	Phone         string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupCustomersRequest) Reset() {
	*x = LookupCustomersRequest{}
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupCustomersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupCustomersRequest) ProtoMessage() {}

func (x *LookupCustomersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupCustomersRequest.ProtoReflect.Descriptor instead.
func (*LookupCustomersRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_customer_proto_rawDescGZIP(), []int{13}
}

func (x *LookupCustomersRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *LookupCustomersRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LookupCustomersRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type LookupCustomersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The garage's own customers matching the contact.
	Data []*Customer `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	// Whether a VietGara user has this verified phone or e-mail. Nothing else
	// about the user is ever returned.
	UserExists    bool `protobuf:"varint,2,opt,name=user_exists,json=userExists,proto3" json:"user_exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupCustomersResponse) Reset() {
	*x = LookupCustomersResponse{}
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupCustomersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupCustomersResponse) ProtoMessage() {}

func (x *LookupCustomersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_customer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupCustomersResponse.ProtoReflect.Descriptor instead.
func (*LookupCustomersResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_customer_proto_rawDescGZIP(), []int{14}
}

func (x *LookupCustomersResponse) GetData() []*Customer {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LookupCustomersResponse) GetUserExists() bool {
	if x != nil {
		return x.UserExists
	}
	return false
}

var File_vietgara_customer_v1_customer_proto protoreflect.FileDescriptor

const file_vietgara_customer_v1_customer_proto_rawDesc = "" +
	"\n" +
	"#vietgara/customer/v1/customer.proto\x12\x14vietgara.customer.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"vietgara/common/v1/lifecycle.proto\x1a#vietgara/common/v1/pagination.proto\"\x86\x05\n" +
	"\bCustomer\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x03R\x02id\x12 \n" +
	"\tgarage_id\x18\x02 \x01(\tB\x03\xe0A\x03R\bgarageId\x12 \n" +
	"\tfull_name\x18\x03 \x01(\tB\x03\xe0A\x02R\bfullName\x12\x19\n" +
	"\x05phone\x18\x04 \x01(\tH\x00R\x05phone\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x05 \x01(\tH\x01R\x05email\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x06 \x01(\tH\x02R\aaddress\x88\x01\x01\x122\n" +
	"\x15personal_data_consent\x18\a \x01(\bR\x13personalDataConsent\x12X\n" +
	"\x18personal_data_consent_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\x15personalDataConsentAt\x12(\n" +
	"\rvehicle_count\x18\t \x01(\x05B\x03\xe0A\x03R\fvehicleCount\x12>\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tcreatedAt\x12>\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tupdatedAt\x12 \n" +
	"\tis_active\x18\f \x01(\bB\x03\xe0A\x03R\bisActive\x12R\n" +
	"\vlink_status\x18\r \x01(\x0e2,.vietgara.customer.v1.CustomerUserLinkStatusB\x03\xe0A\x03R\n" +
	"linkStatusB\b\n" +
	"\x06_phoneB\b\n" +
	"\x06_emailB\n" +
	"\n" +
	"\b_address\"z\n" +
	"\x15CreateCustomerRequest\x12 \n" +
	"\tgarage_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bgarageId\x12?\n" +
	"\bcustomer\x18\x02 \x01(\v2\x1e.vietgara.customer.v1.CustomerB\x03\xe0A\x02R\bcustomer\"T\n" +
	"\x16CreateCustomerResponse\x12:\n" +
	"\bcustomer\x18\x01 \x01(\v2\x1e.vietgara.customer.v1.CustomerR\bcustomer\"\\\n" +
	"\x12GetCustomerRequest\x12 \n" +
	"\tgarage_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bgarageId\x12$\n" +
	"\vcustomer_id\x18\x02 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\"Q\n" +
	"\x13GetCustomerResponse\x12:\n" +
	"\bcustomer\x18\x01 \x01(\v2\x1e.vietgara.customer.v1.CustomerR\bcustomer\"\xdd\x01\n" +
	"\x15UpdateCustomerRequest\x12 \n" +
	"\tgarage_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bgarageId\x12$\n" +
	"\vcustomer_id\x18\x02 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x12?\n" +
	"\bcustomer\x18\x03 \x01(\v2\x1e.vietgara.customer.v1.CustomerB\x03\xe0A\x02R\bcustomer\x12;\n" +
	"\vupdate_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"T\n" +
	"\x16UpdateCustomerResponse\x12:\n" +
	"\bcustomer\x18\x01 \x01(\v2\x1e.vietgara.customer.v1.CustomerR\bcustomer\"\xaa\x01\n" +
	"\x14ListCustomersRequest\x12 \n" +
	"\tgarage_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bgarageId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12)\n" +
	"\x10include_inactive\x18\x05 \x01(\bR\x0fincludeInactive\"\x8b\x01\n" +
	"\x15ListCustomersResponse\x122\n" +
	"\x04data\x18\x01 \x03(\v2\x1e.vietgara.customer.v1.CustomerR\x04data\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.vietgara.common.v1.PaginationR\n" +
	"pagination\"x\n" +
	"\x15DeleteCustomerRequest\x12 \n" +
	"\tgarage_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bgarageId\x12$\n" +
	"\vcustomer_id\x18\x02 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x12\x17\n" +
	"\adry_run\x18\x03 \x01(\bR\x06dryRun\"U\n" +
	"\x16DeleteCustomerResponse\x12;\n" +
	"\aoutcome\x18\x01 \x01(\x0e2!.vietgara.common.v1.DeleteOutcomeR\aoutcome\"a\n" +
	"\x17ActivateCustomerRequest\x12 \n" +
	"\tgarage_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bgarageId\x12$\n" +
	"\vcustomer_id\x18\x02 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\"V\n" +
	"\x18ActivateCustomerResponse\x12:\n" +
	"\bcustomer\x18\x01 \x01(\v2\x1e.vietgara.customer.v1.CustomerR\bcustomer\"f\n" +
	"\x16LookupCustomersRequest\x12 \n" +
	"\tgarage_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bgarageId\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"n\n" +
	"\x17LookupCustomersResponse\x122\n" +
	"\x04data\x18\x01 \x03(\v2\x1e.vietgara.customer.v1.CustomerR\x04data\x12\x1f\n" +
	"\vuser_exists\x18\x02 \x01(\bR\n" +
	"userExists*\xe2\x01\n" +
	"\x16CustomerUserLinkStatus\x12)\n" +
	"%CUSTOMER_USER_LINK_STATUS_UNSPECIFIED\x10\x00\x12'\n" +
	"#CUSTOMER_USER_LINK_STATUS_REQUESTED\x10\x01\x12$\n" +
	" CUSTOMER_USER_LINK_STATUS_LINKED\x10\x02\x12&\n" +
	"\"CUSTOMER_USER_LINK_STATUS_DECLINED\x10\x03\x12&\n" +
	"\"CUSTOMER_USER_LINK_STATUS_UNLINKED\x10\x042\xe0\t\n" +
	"\x0fCustomerService\x12\x97\x01\n" +
	"\rListCustomers\x12*.vietgara.customer.v1.ListCustomersRequest\x1a+.vietgara.customer.v1.ListCustomersResponse\"-\x82\xd3\xe4\x93\x02'\x12%/api/v1/garages/{garage_id}/customers\x12\xae\x01\n" +
	"\x0eCreateCustomer\x12+.vietgara.customer.v1.CreateCustomerRequest\x1a,.vietgara.customer.v1.CreateCustomerResponse\"A\x82\xd3\xe4\x93\x02;:\bcustomerb\bcustomer\"%/api/v1/garages/{garage_id}/customers\x12\xa9\x01\n" +
	"\vGetCustomer\x12(.vietgara.customer.v1.GetCustomerRequest\x1a).vietgara.customer.v1.GetCustomerResponse\"E\x82\xd3\xe4\x93\x02?b\bcustomer\x123/api/v1/garages/{garage_id}/customers/{customer_id}\x12\xbc\x01\n" +
	"\x0eUpdateCustomer\x12+.vietgara.customer.v1.UpdateCustomerRequest\x1a,.vietgara.customer.v1.UpdateCustomerResponse\"O\x82\xd3\xe4\x93\x02I:\bcustomerb\bcustomer23/api/v1/garages/{garage_id}/customers/{customer_id}\x12\xa8\x01\n" +
	"\x0eDeleteCustomer\x12+.vietgara.customer.v1.DeleteCustomerRequest\x1a,.vietgara.customer.v1.DeleteCustomerResponse\";\x82\xd3\xe4\x93\x025*3/api/v1/garages/{garage_id}/customers/{customer_id}\x12\xc4\x01\n" +
	"\x10ActivateCustomer\x12-.vietgara.customer.v1.ActivateCustomerRequest\x1a..vietgara.customer.v1.ActivateCustomerResponse\"Q\x82\xd3\xe4\x93\x02K:\x01*b\bcustomer\"</api/v1/garages/{garage_id}/customers/{customer_id}:activate\x12\xa4\x01\n" +
	"\x0fLookupCustomers\x12,.vietgara.customer.v1.LookupCustomersRequest\x1a-.vietgara.customer.v1.LookupCustomersResponse\"4\x82\xd3\xe4\x93\x02.\x12,/api/v1/garages/{garage_id}/customers/lookupBNZLgithub.com/viettechno/vietgara-proto/apis-go/vietgara/customer/v1;customerv1b\x06proto3"

var (
	file_vietgara_customer_v1_customer_proto_rawDescOnce sync.Once
	file_vietgara_customer_v1_customer_proto_rawDescData []byte
)

func file_vietgara_customer_v1_customer_proto_rawDescGZIP() []byte {
	file_vietgara_customer_v1_customer_proto_rawDescOnce.Do(func() {
		file_vietgara_customer_v1_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vietgara_customer_v1_customer_proto_rawDesc), len(file_vietgara_customer_v1_customer_proto_rawDesc)))
	})
	return file_vietgara_customer_v1_customer_proto_rawDescData
}

var file_vietgara_customer_v1_customer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vietgara_customer_v1_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_vietgara_customer_v1_customer_proto_goTypes = []any{
	(CustomerUserLinkStatus)(0),      // 0: vietgara.customer.v1.CustomerUserLinkStatus
	(*Customer)(nil),                 // 1: vietgara.customer.v1.Customer
	(*CreateCustomerRequest)(nil),    // 2: vietgara.customer.v1.CreateCustomerRequest
	(*CreateCustomerResponse)(nil),   // 3: vietgara.customer.v1.CreateCustomerResponse
	(*GetCustomerRequest)(nil),       // 4: vietgara.customer.v1.GetCustomerRequest
	(*GetCustomerResponse)(nil),      // 5: vietgara.customer.v1.GetCustomerResponse
	(*UpdateCustomerRequest)(nil),    // 6: vietgara.customer.v1.UpdateCustomerRequest
	(*UpdateCustomerResponse)(nil),   // 7: vietgara.customer.v1.UpdateCustomerResponse
	(*ListCustomersRequest)(nil),     // 8: vietgara.customer.v1.ListCustomersRequest
	(*ListCustomersResponse)(nil),    // 9: vietgara.customer.v1.ListCustomersResponse
	(*DeleteCustomerRequest)(nil),    // 10: vietgara.customer.v1.DeleteCustomerRequest
	(*DeleteCustomerResponse)(nil),   // 11: vietgara.customer.v1.DeleteCustomerResponse
	(*ActivateCustomerRequest)(nil),  // 12: vietgara.customer.v1.ActivateCustomerRequest
	(*ActivateCustomerResponse)(nil), // 13: vietgara.customer.v1.ActivateCustomerResponse
	(*LookupCustomersRequest)(nil),   // 14: vietgara.customer.v1.LookupCustomersRequest
	(*LookupCustomersResponse)(nil),  // 15: vietgara.customer.v1.LookupCustomersResponse
	(*timestamppb.Timestamp)(nil),    // 16: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),    // 17: google.protobuf.FieldMask
	(*v1.Pagination)(nil),            // 18: vietgara.common.v1.Pagination
	(v1.DeleteOutcome)(0),            // 19: vietgara.common.v1.DeleteOutcome
}
var file_vietgara_customer_v1_customer_proto_depIdxs = []int32{
	16, // 0: vietgara.customer.v1.Customer.personal_data_consent_at:type_name -> google.protobuf.Timestamp
	16, // 1: vietgara.customer.v1.Customer.created_at:type_name -> google.protobuf.Timestamp
	16, // 2: vietgara.customer.v1.Customer.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: vietgara.customer.v1.Customer.link_status:type_name -> vietgara.customer.v1.CustomerUserLinkStatus
	1,  // 4: vietgara.customer.v1.CreateCustomerRequest.customer:type_name -> vietgara.customer.v1.Customer
	1,  // 5: vietgara.customer.v1.CreateCustomerResponse.customer:type_name -> vietgara.customer.v1.Customer
	1,  // 6: vietgara.customer.v1.GetCustomerResponse.customer:type_name -> vietgara.customer.v1.Customer
	1,  // 7: vietgara.customer.v1.UpdateCustomerRequest.customer:type_name -> vietgara.customer.v1.Customer
	17, // 8: vietgara.customer.v1.UpdateCustomerRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 9: vietgara.customer.v1.UpdateCustomerResponse.customer:type_name -> vietgara.customer.v1.Customer
	1,  // 10: vietgara.customer.v1.ListCustomersResponse.data:type_name -> vietgara.customer.v1.Customer
	18, // 11: vietgara.customer.v1.ListCustomersResponse.pagination:type_name -> vietgara.common.v1.Pagination
	19, // 12: vietgara.customer.v1.DeleteCustomerResponse.outcome:type_name -> vietgara.common.v1.DeleteOutcome
	1,  // 13: vietgara.customer.v1.ActivateCustomerResponse.customer:type_name -> vietgara.customer.v1.Customer
	1,  // 14: vietgara.customer.v1.LookupCustomersResponse.data:type_name -> vietgara.customer.v1.Customer
	8,  // 15: vietgara.customer.v1.CustomerService.ListCustomers:input_type -> vietgara.customer.v1.ListCustomersRequest
	2,  // 16: vietgara.customer.v1.CustomerService.CreateCustomer:input_type -> vietgara.customer.v1.CreateCustomerRequest
	4,  // 17: vietgara.customer.v1.CustomerService.GetCustomer:input_type -> vietgara.customer.v1.GetCustomerRequest
	6,  // 18: vietgara.customer.v1.CustomerService.UpdateCustomer:input_type -> vietgara.customer.v1.UpdateCustomerRequest
	10, // 19: vietgara.customer.v1.CustomerService.DeleteCustomer:input_type -> vietgara.customer.v1.DeleteCustomerRequest
	12, // 20: vietgara.customer.v1.CustomerService.ActivateCustomer:input_type -> vietgara.customer.v1.ActivateCustomerRequest
	14, // 21: vietgara.customer.v1.CustomerService.LookupCustomers:input_type -> vietgara.customer.v1.LookupCustomersRequest
	9,  // 22: vietgara.customer.v1.CustomerService.ListCustomers:output_type -> vietgara.customer.v1.ListCustomersResponse
	3,  // 23: vietgara.customer.v1.CustomerService.CreateCustomer:output_type -> vietgara.customer.v1.CreateCustomerResponse
	5,  // 24: vietgara.customer.v1.CustomerService.GetCustomer:output_type -> vietgara.customer.v1.GetCustomerResponse
	7,  // 25: vietgara.customer.v1.CustomerService.UpdateCustomer:output_type -> vietgara.customer.v1.UpdateCustomerResponse
	11, // 26: vietgara.customer.v1.CustomerService.DeleteCustomer:output_type -> vietgara.customer.v1.DeleteCustomerResponse
	13, // 27: vietgara.customer.v1.CustomerService.ActivateCustomer:output_type -> vietgara.customer.v1.ActivateCustomerResponse
	15, // 28: vietgara.customer.v1.CustomerService.LookupCustomers:output_type -> vietgara.customer.v1.LookupCustomersResponse
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_vietgara_customer_v1_customer_proto_init() }
func file_vietgara_customer_v1_customer_proto_init() {
	if File_vietgara_customer_v1_customer_proto != nil {
		return
	}
	file_vietgara_customer_v1_customer_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vietgara_customer_v1_customer_proto_rawDesc), len(file_vietgara_customer_v1_customer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vietgara_customer_v1_customer_proto_goTypes,
		DependencyIndexes: file_vietgara_customer_v1_customer_proto_depIdxs,
		EnumInfos:         file_vietgara_customer_v1_customer_proto_enumTypes,
		MessageInfos:      file_vietgara_customer_v1_customer_proto_msgTypes,
	}.Build()
	File_vietgara_customer_v1_customer_proto = out.File
	file_vietgara_customer_v1_customer_proto_goTypes = nil
	file_vietgara_customer_v1_customer_proto_depIdxs = nil
}
