// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vietgara/customer/v1/vehicle.proto

package customerv1

import (
	v1 "github.com/viettechno/vietgara-proto/apis-go/vietgara/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Vehicle belongs to one customer of the garage (FR-CUS-02).
type Vehicle struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GarageId     string                 `protobuf:"bytes,2,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	CustomerId   string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerName string                 `protobuf:"bytes,4,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	// Unique per garage (ignoring punctuation and case).
	LicensePlate  string                 `protobuf:"bytes,5,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	Make          *string                `protobuf:"bytes,6,opt,name=make,proto3,oneof" json:"make,omitempty"`
	Model         *string                `protobuf:"bytes,7,opt,name=model,proto3,oneof" json:"model,omitempty"`
	Year          *int32                 `protobuf:"varint,8,opt,name=year,proto3,oneof" json:"year,omitempty"`
	Vin           *string                `protobuf:"bytes,9,opt,name=vin,proto3,oneof" json:"vin,omitempty"`
	EngineNumber  *string                `protobuf:"bytes,10,opt,name=engine_number,json=engineNumber,proto3,oneof" json:"engine_number,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_vietgara_customer_v1_vehicle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_vehicle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_vehicle_proto_rawDescGZIP(), []int{0}
}

func (x *Vehicle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vehicle) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *Vehicle) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Vehicle) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *Vehicle) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *Vehicle) GetMake() string {
	if x != nil && x.Make != nil {
		return *x.Make
	}
	return ""
}

func (x *Vehicle) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *Vehicle) GetYear() int32 {
	if x != nil && x.Year != nil {
		return *x.Year
	}
	return 0
}

func (x *Vehicle) GetVin() string {
	if x != nil && x.Vin != nil {
		return *x.Vin
	}
	return ""
}

func (x *Vehicle) GetEngineNumber() string {
	if x != nil && x.EngineNumber != nil {
		return *x.EngineNumber
	}
	return ""
}

func (x *Vehicle) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Vehicle) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GarageId      string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	Vehicle       *Vehicle               `protobuf:"bytes,2,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVehicleRequest) Reset() {
	*x = CreateVehicleRequest{}
	mi := &file_vietgara_customer_v1_vehicle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVehicleRequest) ProtoMessage() {}

func (x *CreateVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_vehicle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVehicleRequest.ProtoReflect.Descriptor instead.
func (*CreateVehicleRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_vehicle_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVehicleRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *CreateVehicleRequest) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type CreateVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVehicleResponse) Reset() {
	*x = CreateVehicleResponse{}
	mi := &file_vietgara_customer_v1_vehicle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVehicleResponse) ProtoMessage() {}

func (x *CreateVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_vehicle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVehicleResponse.ProtoReflect.Descriptor instead.
func (*CreateVehicleResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_vehicle_proto_rawDescGZIP(), []int{2}
}

func (x *CreateVehicleResponse) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type GetVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GarageId      string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	VehicleId     string                 `protobuf:"bytes,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleRequest) Reset() {
	*x = GetVehicleRequest{}
	mi := &file_vietgara_customer_v1_vehicle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleRequest) ProtoMessage() {}

func (x *GetVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_vehicle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleRequest.ProtoReflect.Descriptor instead.
func (*GetVehicleRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_vehicle_proto_rawDescGZIP(), []int{3}
}

func (x *GetVehicleRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *GetVehicleRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

type GetVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleResponse) Reset() {
	*x = GetVehicleResponse{}
	mi := &file_vietgara_customer_v1_vehicle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleResponse) ProtoMessage() {}

func (x *GetVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_vehicle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleResponse.ProtoReflect.Descriptor instead.
func (*GetVehicleResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_vehicle_proto_rawDescGZIP(), []int{4}
}

func (x *GetVehicleResponse) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type UpdateVehicleRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	GarageId  string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	VehicleId string                 `protobuf:"bytes,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	// customer_id may move the vehicle to another customer of the garage.
	Vehicle *Vehicle `protobuf:"bytes,3,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	// Filled from the JSON body keys when omitted.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVehicleRequest) Reset() {
	*x = UpdateVehicleRequest{}
	mi := &file_vietgara_customer_v1_vehicle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleRequest) ProtoMessage() {}

func (x *UpdateVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_vehicle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleRequest.ProtoReflect.Descriptor instead.
func (*UpdateVehicleRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_vehicle_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateVehicleRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *UpdateVehicleRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *UpdateVehicleRequest) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

func (x *UpdateVehicleRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVehicleResponse) Reset() {
	*x = UpdateVehicleResponse{}
	mi := &file_vietgara_customer_v1_vehicle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleResponse) ProtoMessage() {}

func (x *UpdateVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_vehicle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleResponse.ProtoReflect.Descriptor instead.
func (*UpdateVehicleResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_vehicle_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateVehicleResponse) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type ListVehiclesRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	GarageId string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	// Only this customer's vehicles.
	CustomerId string `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Matches license plate, make or model.
	Query         string `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesRequest) Reset() {
	*x = ListVehiclesRequest{}
	mi := &file_vietgara_customer_v1_vehicle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesRequest) ProtoMessage() {}

func (x *ListVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_vehicle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesRequest.ProtoReflect.Descriptor instead.
func (*ListVehiclesRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_vehicle_proto_rawDescGZIP(), []int{7}
}

func (x *ListVehiclesRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *ListVehiclesRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ListVehiclesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListVehiclesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListVehiclesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListVehiclesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Vehicle             `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *v1.Pagination         `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesResponse) Reset() {
	*x = ListVehiclesResponse{}
	mi := &file_vietgara_customer_v1_vehicle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesResponse) ProtoMessage() {}

func (x *ListVehiclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_vehicle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesResponse.ProtoReflect.Descriptor instead.
func (*ListVehiclesResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_vehicle_proto_rawDescGZIP(), []int{8}
}

func (x *ListVehiclesResponse) GetData() []*Vehicle {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListVehiclesResponse) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type DeleteVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GarageId      string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	VehicleId     string                 `protobuf:"bytes,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVehicleRequest) Reset() {
	*x = DeleteVehicleRequest{}
	mi := &file_vietgara_customer_v1_vehicle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVehicleRequest) ProtoMessage() {}

func (x *DeleteVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_vehicle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVehicleRequest.ProtoReflect.Descriptor instead.
func (*DeleteVehicleRequest) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_vehicle_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteVehicleRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *DeleteVehicleRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

type DeleteVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVehicleResponse) Reset() {
	*x = DeleteVehicleResponse{}
	mi := &file_vietgara_customer_v1_vehicle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVehicleResponse) ProtoMessage() {}

func (x *DeleteVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vietgara_customer_v1_vehicle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVehicleResponse.ProtoReflect.Descriptor instead.
func (*DeleteVehicleResponse) Descriptor() ([]byte, []int) {
	return file_vietgara_customer_v1_vehicle_proto_rawDescGZIP(), []int{10}
}

var File_vietgara_customer_v1_vehicle_proto protoreflect.FileDescriptor

const file_vietgara_customer_v1_vehicle_proto_rawDesc = "" +
	"\n" +
	"\"vietgara/customer/v1/vehicle.proto\x12\x14vietgara.customer.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#vietgara/common/v1/pagination.proto\"\xfe\x03\n" +
	"\aVehicle\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x03R\x02id\x12 \n" +
	"\tgarage_id\x18\x02 \x01(\tB\x03\xe0A\x03R\bgarageId\x12$\n" +
	"\vcustomer_id\x18\x03 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x12(\n" +
	"\rcustomer_name\x18\x04 \x01(\tB\x03\xe0A\x03R\fcustomerName\x12(\n" +
	"\rlicense_plate\x18\x05 \x01(\tB\x03\xe0A\x02R\flicensePlate\x12\x17\n" +
	"\x04make\x18\x06 \x01(\tH\x00R\x04make\x88\x01\x01\x12\x19\n" +
	"\x05model\x18\a \x01(\tH\x01R\x05model\x88\x01\x01\x12\x17\n" +
	"\x04year\x18\b \x01(\x05H\x02R\x04year\x88\x01\x01\x12\x15\n" +
	"\x03vin\x18\t \x01(\tH\x03R\x03vin\x88\x01\x01\x12(\n" +
	"\rengine_number\x18\n" +
	" \x01(\tH\x04R\fengineNumber\x88\x01\x01\x12>\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tcreatedAt\x12>\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tupdatedAtB\a\n" +
	"\x05_makeB\b\n" +
	"\x06_modelB\a\n" +
	"\x05_yearB\x06\n" +
	"\x04_vinB\x10\n" +
	"\x0e_engine_number\"v\n" +
	"\x14CreateVehicleRequest\x12 \n" +
	"\tgarage_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bgarageId\x12<\n" +
	"\avehicle\x18\x02 \x01(\v2\x1d.vietgara.customer.v1.VehicleB\x03\xe0A\x02R\avehicle\"P\n" +
	"\x15CreateVehicleResponse\x127\n" +
	"\avehicle\x18\x01 \x01(\v2\x1d.vietgara.customer.v1.VehicleR\avehicle\"Y\n" +
	"\x11GetVehicleRequest\x12 \n" +
	"\tgarage_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bgarageId\x12\"\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\tB\x03\xe0A\x02R\tvehicleId\"M\n" +
	"\x12GetVehicleResponse\x127\n" +
	"\avehicle\x18\x01 \x01(\v2\x1d.vietgara.customer.v1.VehicleR\avehicle\"\xd7\x01\n" +
	"\x14UpdateVehicleRequest\x12 \n" +
	"\tgarage_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bgarageId\x12\"\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\tB\x03\xe0A\x02R\tvehicleId\x12<\n" +
	"\avehicle\x18\x03 \x01(\v2\x1d.vietgara.customer.v1.VehicleB\x03\xe0A\x02R\avehicle\x12;\n" +
	"\vupdate_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"P\n" +
	"\x15UpdateVehicleResponse\x127\n" +
	"\avehicle\x18\x01 \x01(\v2\x1d.vietgara.customer.v1.VehicleR\avehicle\"\x9f\x01\n" +
	"\x13ListVehiclesRequest\x12 \n" +
	"\tgarage_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bgarageId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"\x89\x01\n" +
	"\x14ListVehiclesResponse\x121\n" +
	"\x04data\x18\x01 \x03(\v2\x1d.vietgara.customer.v1.VehicleR\x04data\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.vietgara.common.v1.PaginationR\n" +
	"pagination\"\\\n" +
	"\x14DeleteVehicleRequest\x12 \n" +
	"\tgarage_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bgarageId\x12\"\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\tB\x03\xe0A\x02R\tvehicleId\"\x17\n" +
	"\x15DeleteVehicleResponse2\xd5\x06\n" +
	"\x0eVehicleService\x12\x93\x01\n" +
	"\fListVehicles\x12).vietgara.customer.v1.ListVehiclesRequest\x1a*.vietgara.customer.v1.ListVehiclesResponse\",\x82\xd3\xe4\x93\x02&\x12$/api/v1/garages/{garage_id}/vehicles\x12\xa8\x01\n" +
	"\rCreateVehicle\x12*.vietgara.customer.v1.CreateVehicleRequest\x1a+.vietgara.customer.v1.CreateVehicleResponse\">\x82\xd3\xe4\x93\x028:\avehicleb\avehicle\"$/api/v1/garages/{garage_id}/vehicles\x12\xa3\x01\n" +
	"\n" +
	"GetVehicle\x12'.vietgara.customer.v1.GetVehicleRequest\x1a(.vietgara.customer.v1.GetVehicleResponse\"B\x82\xd3\xe4\x93\x02<b\avehicle\x121/api/v1/garages/{garage_id}/vehicles/{vehicle_id}\x12\xb5\x01\n" +
	"\rUpdateVehicle\x12*.vietgara.customer.v1.UpdateVehicleRequest\x1a+.vietgara.customer.v1.UpdateVehicleResponse\"K\x82\xd3\xe4\x93\x02E:\avehicleb\avehicle21/api/v1/garages/{garage_id}/vehicles/{vehicle_id}\x12\xa3\x01\n" +
	"\rDeleteVehicle\x12*.vietgara.customer.v1.DeleteVehicleRequest\x1a+.vietgara.customer.v1.DeleteVehicleResponse\"9\x82\xd3\xe4\x93\x023*1/api/v1/garages/{garage_id}/vehicles/{vehicle_id}BNZLgithub.com/viettechno/vietgara-proto/apis-go/vietgara/customer/v1;customerv1b\x06proto3"

var (
	file_vietgara_customer_v1_vehicle_proto_rawDescOnce sync.Once
	file_vietgara_customer_v1_vehicle_proto_rawDescData []byte
)

func file_vietgara_customer_v1_vehicle_proto_rawDescGZIP() []byte {
	file_vietgara_customer_v1_vehicle_proto_rawDescOnce.Do(func() {
		file_vietgara_customer_v1_vehicle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vietgara_customer_v1_vehicle_proto_rawDesc), len(file_vietgara_customer_v1_vehicle_proto_rawDesc)))
	})
	return file_vietgara_customer_v1_vehicle_proto_rawDescData
}

var file_vietgara_customer_v1_vehicle_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_vietgara_customer_v1_vehicle_proto_goTypes = []any{
	(*Vehicle)(nil),               // 0: vietgara.customer.v1.Vehicle
	(*CreateVehicleRequest)(nil),  // 1: vietgara.customer.v1.CreateVehicleRequest
	(*CreateVehicleResponse)(nil), // 2: vietgara.customer.v1.CreateVehicleResponse
	(*GetVehicleRequest)(nil),     // 3: vietgara.customer.v1.GetVehicleRequest
	(*GetVehicleResponse)(nil),    // 4: vietgara.customer.v1.GetVehicleResponse
	(*UpdateVehicleRequest)(nil),  // 5: vietgara.customer.v1.UpdateVehicleRequest
	(*UpdateVehicleResponse)(nil), // 6: vietgara.customer.v1.UpdateVehicleResponse
	(*ListVehiclesRequest)(nil),   // 7: vietgara.customer.v1.ListVehiclesRequest
	(*ListVehiclesResponse)(nil),  // 8: vietgara.customer.v1.ListVehiclesResponse
	(*DeleteVehicleRequest)(nil),  // 9: vietgara.customer.v1.DeleteVehicleRequest
	(*DeleteVehicleResponse)(nil), // 10: vietgara.customer.v1.DeleteVehicleResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 12: google.protobuf.FieldMask
	(*v1.Pagination)(nil),         // 13: vietgara.common.v1.Pagination
}
var file_vietgara_customer_v1_vehicle_proto_depIdxs = []int32{
	11, // 0: vietgara.customer.v1.Vehicle.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: vietgara.customer.v1.Vehicle.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: vietgara.customer.v1.CreateVehicleRequest.vehicle:type_name -> vietgara.customer.v1.Vehicle
	0,  // 3: vietgara.customer.v1.CreateVehicleResponse.vehicle:type_name -> vietgara.customer.v1.Vehicle
	0,  // 4: vietgara.customer.v1.GetVehicleResponse.vehicle:type_name -> vietgara.customer.v1.Vehicle
	0,  // 5: vietgara.customer.v1.UpdateVehicleRequest.vehicle:type_name -> vietgara.customer.v1.Vehicle
	12, // 6: vietgara.customer.v1.UpdateVehicleRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 7: vietgara.customer.v1.UpdateVehicleResponse.vehicle:type_name -> vietgara.customer.v1.Vehicle
	0,  // 8: vietgara.customer.v1.ListVehiclesResponse.data:type_name -> vietgara.customer.v1.Vehicle
	13, // 9: vietgara.customer.v1.ListVehiclesResponse.pagination:type_name -> vietgara.common.v1.Pagination
	7,  // 10: vietgara.customer.v1.VehicleService.ListVehicles:input_type -> vietgara.customer.v1.ListVehiclesRequest
	1,  // 11: vietgara.customer.v1.VehicleService.CreateVehicle:input_type -> vietgara.customer.v1.CreateVehicleRequest
	3,  // 12: vietgara.customer.v1.VehicleService.GetVehicle:input_type -> vietgara.customer.v1.GetVehicleRequest
	5,  // 13: vietgara.customer.v1.VehicleService.UpdateVehicle:input_type -> vietgara.customer.v1.UpdateVehicleRequest
	9,  // 14: vietgara.customer.v1.VehicleService.DeleteVehicle:input_type -> vietgara.customer.v1.DeleteVehicleRequest
	8,  // 15: vietgara.customer.v1.VehicleService.ListVehicles:output_type -> vietgara.customer.v1.ListVehiclesResponse
	2,  // 16: vietgara.customer.v1.VehicleService.CreateVehicle:output_type -> vietgara.customer.v1.CreateVehicleResponse
	4,  // 17: vietgara.customer.v1.VehicleService.GetVehicle:output_type -> vietgara.customer.v1.GetVehicleResponse
	6,  // 18: vietgara.customer.v1.VehicleService.UpdateVehicle:output_type -> vietgara.customer.v1.UpdateVehicleResponse
	10, // 19: vietgara.customer.v1.VehicleService.DeleteVehicle:output_type -> vietgara.customer.v1.DeleteVehicleResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_vietgara_customer_v1_vehicle_proto_init() }
func file_vietgara_customer_v1_vehicle_proto_init() {
	if File_vietgara_customer_v1_vehicle_proto != nil {
		return
	}
	file_vietgara_customer_v1_vehicle_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vietgara_customer_v1_vehicle_proto_rawDesc), len(file_vietgara_customer_v1_vehicle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vietgara_customer_v1_vehicle_proto_goTypes,
		DependencyIndexes: file_vietgara_customer_v1_vehicle_proto_depIdxs,
		MessageInfos:      file_vietgara_customer_v1_vehicle_proto_msgTypes,
	}.Build()
	File_vietgara_customer_v1_vehicle_proto = out.File
	file_vietgara_customer_v1_vehicle_proto_goTypes = nil
	file_vietgara_customer_v1_vehicle_proto_depIdxs = nil
}
