// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: vietgara/reporting/v1/reporting.proto

package reportingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReportingService_GetRevenueReport_FullMethodName = "/vietgara.reporting.v1.ReportingService/GetRevenueReport"
)

// ReportingServiceClient is the client API for ReportingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ReportingService serves the revenue-by-period report (FR-RPT-01) that
// backs the Web Admin Dashboard's KPI card and revenue chart (UI Design
// Spec 3.1). It owns no tables of its own -- revenue is aggregated fresh
// from Billing & Settlement's settlements on every request, the same
// cross-module decoupling pattern used everywhere else (HLD Section 2).
// Every other Dashboard KPI (orders in progress, low stock, outstanding
// receivables) is served by each owning module's existing list endpoint;
// this is the one figure not already exposed anywhere.
type ReportingServiceClient interface {
	GetRevenueReport(ctx context.Context, in *GetRevenueReportRequest, opts ...grpc.CallOption) (*GetRevenueReportResponse, error)
}

type reportingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReportingServiceClient(cc grpc.ClientConnInterface) ReportingServiceClient {
	return &reportingServiceClient{cc}
}

func (c *reportingServiceClient) GetRevenueReport(ctx context.Context, in *GetRevenueReportRequest, opts ...grpc.CallOption) (*GetRevenueReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRevenueReportResponse)
	err := c.cc.Invoke(ctx, ReportingService_GetRevenueReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportingServiceServer is the server API for ReportingService service.
// All implementations must embed UnimplementedReportingServiceServer
// for forward compatibility.
//
// ReportingService serves the revenue-by-period report (FR-RPT-01) that
// backs the Web Admin Dashboard's KPI card and revenue chart (UI Design
// Spec 3.1). It owns no tables of its own -- revenue is aggregated fresh
// from Billing & Settlement's settlements on every request, the same
// cross-module decoupling pattern used everywhere else (HLD Section 2).
// Every other Dashboard KPI (orders in progress, low stock, outstanding
// receivables) is served by each owning module's existing list endpoint;
// this is the one figure not already exposed anywhere.
type ReportingServiceServer interface {
	GetRevenueReport(context.Context, *GetRevenueReportRequest) (*GetRevenueReportResponse, error)
	mustEmbedUnimplementedReportingServiceServer()
}

// UnimplementedReportingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReportingServiceServer struct{}

func (UnimplementedReportingServiceServer) GetRevenueReport(context.Context, *GetRevenueReportRequest) (*GetRevenueReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRevenueReport not implemented")
}
func (UnimplementedReportingServiceServer) mustEmbedUnimplementedReportingServiceServer() {}
func (UnimplementedReportingServiceServer) testEmbeddedByValue()                          {}

// UnsafeReportingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportingServiceServer will
// result in compilation errors.
type UnsafeReportingServiceServer interface {
	mustEmbedUnimplementedReportingServiceServer()
}

func RegisterReportingServiceServer(s grpc.ServiceRegistrar, srv ReportingServiceServer) {
	// If the following call panics, it indicates UnimplementedReportingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReportingService_ServiceDesc, srv)
}

func _ReportingService_GetRevenueReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRevenueReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportingServiceServer).GetRevenueReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportingService_GetRevenueReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportingServiceServer).GetRevenueReport(ctx, req.(*GetRevenueReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReportingService_ServiceDesc is the grpc.ServiceDesc for ReportingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReportingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vietgara.reporting.v1.ReportingService",
	HandlerType: (*ReportingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRevenueReport",
			Handler:    _ReportingService_GetRevenueReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vietgara/reporting/v1/reporting.proto",
}
